// peDeals - eight more end-to-end PE case studies for the Deal Room, each a
// DIFFERENT private-equity playbook so no two feel alike:
//   2. Turnaround        - a money-losing diner chain
//   3. Roll-up           - an HVAC platform + bolt-ons
//   4. Carve-out         - a division spun out of a conglomerate
//   5. Take-private      - buying a small public company
//   6. Growth equity     - a minority stake in a fast-growing DTC brand
//   7. Family succession - a third-generation family boat maker
//   8. Distressed        - a retailer bought out of near-bankruptcy
//   9. Healthcare build  - a dental-clinic roll-up
//
// Same engine as the flagship deal (emails, decisions, real multi-round
// negotiations, a MOIC scorecard). Diane Okafor at Meridian is your partner
// across every deal; each company brings its own cast, twist, and numbers.
// Option lengths are kept ~equal and the component shuffles their order.

import type { Deal } from "./peDealRoom"

const DIANE = { name: "Diane Okafor", role: "Managing Partner, Meridian Capital" }

/* ═══════════════ 2 · TURNAROUND — Blue Plate Diners ═══════════════ */
const turnaround: Deal = {
  id: "blueplate", company: "Blue Plate Diners", strategy: "Turnaround", sector: "Casual dining",
  tagline: "A 60-location diner chain bleeding cash — buy it cheap, fix it, or lose your shirt.", difficulty: "Advanced", emoji: "🥞",
  initVars: { ebitda: 4, leverageMult: 3, holdYears: 4 },
  steps: [
    { kind: "email", id: "bp-intro", phase: "Onboarding", from: DIANE, subject: "A messy one — want it?",
      body: ["Blue Plate Diners: 60 all-day breakfast spots, beloved food, and it's quietly losing money. The founder's estate wants out fast.",
        "This is a turnaround - higher risk, but if you fix the operations you can double the profit. Fumble it and we lose real money. Interested?"],
      cta: "Take a look" },
    { kind: "document", id: "bp-cim", phase: "Sourcing", title: "Blue Plate Diners — deal book", subtitle: "Distressed sale · all-day diner chain",
      rows: [{ k: "Locations", v: "60 (12 lose money)" }, { k: "Revenue", v: "$120M" }, { k: "EBITDA", v: "$4M (down from $11M)" }, { k: "Brand", v: "Loved — lines out the door at the good ones" }, { k: "Problem", v: "Bloated menu, bad locations, no systems" }],
      highlights: ["Great food and a real brand people love", "Best 40 diners are genuinely profitable", "Costs and menu have never been managed"],
      risks: ["12 locations bleed cash every month", "Food costs are wildly out of control", "One more bad year and lenders step in"],
      cta: "Close the book" },
    { kind: "decision", id: "bp-fit", phase: "Sourcing", situation: ["The brand is loved but the business is a mess. Diane wants your read."],
      question: "Is this turnaround worth doing?",
      choices: [
        { text: "Yes - loved brand, fixable ops, priced for the mess", points: 2, rel: 2, feedback: "The turnaround thesis: the brand is the hard part to build, and it's already there. The mess is why it's cheap.", effect: { buildQuality: 4 } },
        { text: "No - a money-loser is never worth the risk", points: 0, feedback: "A profitable, fixed chain would cost 3× this. The losses ARE the opportunity - if you can fix them." },
        { text: "Only if the estate turns it around first", points: 1, feedback: "They can't and won't - that's why they're selling. You're the turnaround; that's the whole job." },
      ] },
    { kind: "meeting", id: "bp-mgmt", phase: "Diligence", person: { name: "Sal Moretti", role: "COO, Blue Plate Diners" }, pickCount: 3,
      intro: ["Sal's run operations for 20 years and stayed through the decline. Three questions before he heads to the lunch rush."],
      questions: [
        { q: "Which locations lose money, and why?", a: "\"Twelve. Mostly bad leases and dead neighborhoods - not the food. The other 48 are solid.\"", key: true },
        { q: "Why did food costs blow up?", a: "\"Every diner orders on its own, no menu discipline. We have 90 menu items. Ninety! It's chaos.\"", key: true },
        { q: "Can the good diners grow?", a: "\"Absolutely - the strong ones are packed. We just never had money to fix the weak ones or invest.\"", key: true },
        { q: "What's the most popular dish?", a: "\"The short stack. But you didn't buy a pancake, you bought a business.\"", key: false },
        { q: "How old are the buildings?", a: "\"Varies. Charming, mostly irrelevant to your problem.\"", key: false },
        { q: "Do staff stick around?", a: "\"The good locations, yes. Great crews. Worth protecting.\"", key: false },
      ] },
    { kind: "decision", id: "bp-structure", phase: "Negotiation", from: DIANE, subject: "Debt on a turnaround?",
      situation: ["A wobbly business plus debt is a dangerous mix. Decide the leverage before you bid."],
      question: "How much debt do you use?",
      choices: [
        { text: "Light debt - a shaky turnaround needs breathing room", points: 2, feedback: "Leverage multiplies both outcomes. On a turnaround, low debt means one bad quarter doesn't end you.", effect: { leverageMult: 2 } },
        { text: "Heavy debt to juice the upside", points: 0, feedback: "Pile debt on a money-loser and the first slow month hands it to the bank. This is how turnarounds die.", effect: { leverageMult: 5 } },
        { text: "No debt at all, pure caution", points: 1, feedback: "Safe, but it mutes your return on a deal that can genuinely fly. A little leverage was fine here.", effect: { leverageMult: 0.5 } },
      ] },
    { kind: "negotiation", id: "bp-loi", phase: "Negotiation",
      neg: { id: "bp-loi", title: "The LOI — steal it, but keep it fair", counterparty: "Grace Tan", role: "Estate's advisor", youWant: "low", unit: "×", start: 5.5, floor: 4, resultVar: "entryMultiple",
        intro: ["The estate wants a fast, clean sale.", "Grace: \"They're realistic - they know it's struggling. But don't insult a brand this loved. Where are you?\""],
        rounds: [
          { theirLine: "\"We're hoping for around 5.5× the current profit.\"",
            choices: [
              { text: "Offer 4.2× and show the 12 losing sites", reply: "\"...the losing locations are hard to argue with. Let me take a real number back.\"", move: 1, rel: 5, points: 2, feedback: "Anchoring on the actual problem sites is honest AND effective - a fact-based low offer they can accept." },
              { text: "Split at 5× to move fast", reply: "\"Sure, that's close to the ask - easy for us to say yes.\"", move: 0.3, rel: 2, points: 1, feedback: "Fast, but you left money on the table by anchoring near their number on a distressed asset." },
              { text: "Lowball 3× and call it junk", reply: "\"It's a loved brand, not junk. That's not serious.\"", move: 0.1, rel: -8, points: 0, feedback: "Trashing a loved brand to a grieving estate kills goodwill and barely moves the price." },
            ] },
          { theirLine: "\"Closer. Give the family a reason to sign with you.\"",
            choices: [
              { text: "Promise to save the good diners and their crews", reply: "\"That matters to them more than the last half-turn. Done - you've got it.\"", move: 1, rel: 6, points: 2, feedback: "Non-price terms win distressed founder deals. You closed the gap without overpaying." },
              { text: "Bump your price a little to seal it", reply: "\"Appreciated - every turn you give, they take.\"", move: 0.5, rel: 2, points: 1, feedback: "Conceding on price with nothing back just raises your entry cost and dents the MOIC." },
              { text: "Threaten to walk", reply: "\"On a fast, friendly sale? Odd move.\"", move: 0.2, rel: -5, points: 0, feedback: "A walk-away threat with no leverage just weakens you." },
            ] },
        ] } },
    { kind: "decision", id: "bp-dd", phase: "Diligence", subject: "Diligence: a health-code problem",
      situation: ["Your team finds three of the good locations have lapsed health inspections - fixable, but embarrassing if it leaks."],
      question: "How do you handle it?",
      choices: [
        { text: "Budget the fixes and factor them into the plan", points: 2, feedback: "Fixable and known - price it, plan it, move on. This is exactly what diligence is for.", effect: { buildQuality: 3, score: 1 } },
        { text: "Ignore it - three sites out of sixty", points: 1, feedback: "A single viral health story can tank a food brand. Small problems in food are not optional to fix." },
        { text: "Blow up the deal over it", points: 0, feedback: "Three fixable inspections aren't a reason to kill a thesis-perfect turnaround. Price it, don't panic.", effect: { buildQuality: -3 } },
      ] },
    { kind: "milestone", id: "bp-closed", phase: "Closing", variant: "closed", title: "You own Blue Plate — now save it",
      body: ["The keys (and a lot of problems) are yours. The clock starts now: fix the bleeding before the next slow season."] },
    { kind: "decision", id: "bp-v1", phase: "Value Creation", situation: ["Week one. Where do you start the turnaround?"],
      question: "Your first move?",
      choices: [
        { text: "Close the 12 losers, cut the menu to 30 hits", points: 2, feedback: "Stop the bleeding and simplify. Fewer items means lower food cost, faster service, happier crews - the core fix.", effect: { buildQuality: 8, score: 1 } },
        { text: "Keep every location and every menu item", points: 0, feedback: "Loyalty to money-losing sites and a 90-item menu is what nearly killed it. You must cut to save it.", effect: { buildQuality: -6 } },
        { text: "Raise prices everywhere to cover the losses", points: 1, feedback: "Price hikes without fixing the mess just push customers away from the diners that still work.", effect: { buildQuality: -1 } },
      ] },
    { kind: "decision", id: "bp-v2", phase: "Value Creation", subject: "The turnaround is working",
      situation: ["Two years in, the trimmed chain is profitable again. You have cash to reinvest."],
      question: "What now?",
      choices: [
        { text: "Reinvest in the strong diners and open a few new ones", points: 2, feedback: "Now that the base is healthy, disciplined growth compounds it. This is where the real return is made.", effect: { buildQuality: 7, score: 1 } },
        { text: "Pay yourself a big dividend and coast", points: 1, feedback: "Taking chips early is fine, but you'd leave the growth - the best part - on the table.", effect: { buildQuality: -1 } },
        { text: "Rush back into the markets you just exited", points: 0, feedback: "Re-opening in the dead neighborhoods you fled repeats the original mistake. Grow where it works.", effect: { buildQuality: -5 } },
      ] },
    { kind: "email", id: "bp-exit", phase: "Exit", from: { name: "Marcus Lin", role: "Harbor Point Advisors" }, subject: "Time to sell the comeback",
      body: ["Blue Plate is a genuine turnaround story now - lean, profitable, growing. A national restaurant group and a franchisor both want it.", "Let's sell the comeback while the numbers are shining."], cta: "Run the exit" },
    { kind: "negotiation", id: "bp-exit-neg", phase: "Exit",
      neg: { id: "bp-exit", title: "The exit — sell the comeback", counterparty: "National Restaurant Group", role: "Buyer's M&A lead", youWant: "high", unit: "×", start: 5, floor: 7.5, resultVar: "exitMultiple",
        intro: ["A national group wants your fixed chain.", "\"It's a nice turnaround. We're thinking 5×,\" their lead offers."],
        rounds: [
          { theirLine: "\"5× feels right for a regional chain.\"",
            choices: [
              { text: "Show the growth curve and the franchise upside", reply: "\"...the trajectory is real, and franchising is worth a lot to us. Let's go higher.\"", move: 1.5, rel: 5, points: 2, feedback: "You priced it on its future and on what it's worth to THEM. That's the seller's best lever." },
              { text: "Ask for 'a bit more' vaguely", reply: "\"We can nudge it a touch.\"", move: 0.5, rel: 2, points: 1, feedback: "Vague asks get vague moves. Anchor to a number and a reason." },
              { text: "Demand double or walk", reply: "\"That's not a negotiation. We have options.\"", move: 0.1, rel: -8, points: 0, feedback: "Extreme demands with no basis invite them to walk." },
            ] },
          { theirLine: "\"Give us a reason to reach the top of our range.\"",
            choices: [
              { text: "Remind them the franchisor is also bidding", reply: "\"...we don't want to lose it. Top of range, and we move fast.\"", move: 1.3, rel: 4, points: 2, feedback: "A live rival bidder is what turns a fair price into a full one." },
              { text: "Take their number to lock the win", reply: "\"Smart to take certainty.\"", move: 0, rel: 3, points: 1, feedback: "Certainty has value, but with a rival bidding you had one more push in you." },
              { text: "Bluff a fake higher offer", reply: "\"We checked. That offer doesn't exist.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff destroys your credibility and your price." },
            ] },
        ] } },
    { kind: "milestone", id: "bp-exit-done", phase: "Exit", variant: "exit", title: "Exited — the comeback pays off",
      body: ["Blue Plate sells as a lean, growing chain. The crews you protected keep their jobs under the new owner.", "Diane: \"Turnarounds are the hardest money in this business. Nicely done.\""] },
  ],
}

/* ═══════════════ 3 · ROLL-UP — Summit Comfort ═══════════════ */
const rollup: Deal = {
  id: "summit", company: "Summit Comfort", strategy: "Roll-up", sector: "HVAC services",
  tagline: "Buy one great heating-and-cooling company, then bolt on its rivals to build a giant.", difficulty: "Core", emoji: "❄️",
  initVars: { ebitda: 6, leverageMult: 4, holdYears: 5 },
  steps: [
    { kind: "email", id: "su-intro", phase: "Onboarding", from: DIANE, subject: "A platform for a roll-up",
      body: ["The home-services world - heating, cooling, plumbing - is thousands of small family shops and no big winner. Classic roll-up territory.",
        "Summit Comfort is a strong regional HVAC company we'd buy as the 'platform', then bolt on smaller rivals. Small shops sell for ~4× profit; a big combined one sells for ~9×. That gap is the whole game."],
      cta: "Study the platform" },
    { kind: "document", id: "su-cim", phase: "Sourcing", title: "Summit Comfort — platform profile", subtitle: "Regional HVAC services · roll-up platform",
      rows: [{ k: "Business", v: "Install & service heating/cooling systems" }, { k: "Revenue", v: "$45M" }, { k: "EBITDA", v: "$6M" }, { k: "Techs", v: "180, strong reputation" }, { k: "Market", v: "Fragmented — 100s of tiny rivals nearby" }],
      highlights: ["Great brand and a real management team to build on", "Recurring service contracts = steady cash flow", "Dozens of small rivals that could be bolted on"],
      risks: ["Hard to hire enough skilled technicians", "Roll-ups fail if you don't integrate what you buy", "Seasonal swings in demand"],
      cta: "Close the profile" },
    { kind: "decision", id: "su-fit", phase: "Sourcing", situation: ["Why does a roll-up create value here? Diane wants you to nail the thesis."],
      question: "What makes this strategy powerful?",
      choices: [
        { text: "Small shops bought at 4× become worth 9× inside a big one", points: 2, rel: 2, feedback: "Multiple arbitrage: size itself makes the same profit more valuable. That gap is the return.", effect: { buildQuality: 4 } },
        { text: "Buying lots of companies just looks impressive", points: 0, feedback: "Empire-building with no value logic is how roll-ups collapse. Every buy needs a reason." },
        { text: "It wipes out all the competition entirely", points: 1, feedback: "With hundreds of rivals you'll never monopolize - and trying invites regulators. The prize is the valuation math." },
      ] },
    { kind: "decision", id: "su-structure", phase: "Negotiation", from: DIANE, subject: "Structure the platform buy",
      situation: ["You'll need dry powder for future bolt-ons, not just this first buy. Size the debt with that in mind."],
      question: "How do you structure it?",
      choices: [
        { text: "Sensible debt, keeping cash free for bolt-ons", points: 2, feedback: "A roll-up lives on follow-on buys. Over-levering the platform leaves you unable to actually roll up.", effect: { leverageMult: 4 } },
        { text: "Max debt now to minimize your check", points: 1, feedback: "Tapped out on day one, you can't fund the bolt-ons that make the strategy work.", effect: { leverageMult: 5.5 } },
        { text: "All cash, no debt ever", points: 1, feedback: "Very safe, but you give up the leverage that lifts roll-up returns. A balance was better.", effect: { leverageMult: 1 } },
      ] },
    { kind: "negotiation", id: "su-loi", phase: "Negotiation",
      neg: { id: "su-loi", title: "The LOI — buy the platform", counterparty: "Ray Whitfield", role: "Founder, Summit Comfort", youWant: "low", unit: "×", start: 7, floor: 5.5, resultVar: "entryMultiple",
        intro: ["Ray built Summit over 30 years and will stay to help you grow it.", "\"I want a partner who'll grow this right,\" he says. \"But I've earned a fair price. Where do we start?\""],
        rounds: [
          { theirLine: "\"I'm thinking 7× - this is a premium platform.\"",
            choices: [
              { text: "Offer 5.7× with comps, and a big growth vision", reply: "\"...the number's fair and I love the plan. Let's keep talking.\"", move: 0.9, rel: 5, points: 2, feedback: "Pair a fair, comps-based price with the exciting future - founders sell to the plan." },
              { text: "Meet near 6.7× to keep him happy", reply: "\"Generous of you - I'll take it.\"", move: 0.3, rel: 3, points: 1, feedback: "Overpaying to be liked hurts the MOIC. Fair, not generous, wins good founders." },
              { text: "Lowball 4× - it's just HVAC", reply: "\"Just HVAC? I'll find another buyer.\"", move: 0.1, rel: -8, points: 0, feedback: "Belittling his life's work ends the deal - and platforms are hard to find." },
            ] },
          { theirLine: "\"Close the gap and let's shake.\"",
            choices: [
              { text: "Offer him a rollover stake in the bigger company", reply: "\"Now that's a partnership. Deal.\"", move: 0.9, rel: 6, points: 2, feedback: "A rollover aligns the founder with the roll-up's upside - and closes the price gap smartly." },
              { text: "Just pay up to finish it", reply: "\"Works for me - every turn's yours to give.\"", move: 0.5, rel: 2, points: 1, feedback: "Paying up closes deals but at the cost of your entry price." },
              { text: "Play hardball at the buzzer", reply: "\"After all that? Leaves a bad taste for a partnership.\"", move: 0.3, rel: -5, points: 1, feedback: "Squeezing a partner you'll work with for years rarely pays." },
            ] },
        ] } },
    { kind: "milestone", id: "su-closed", phase: "Closing", variant: "closed", title: "Platform acquired — now roll it up",
      body: ["Summit Comfort is yours, with Ray alongside. Time to find the bolt-ons that turn a good company into a giant."] },
    { kind: "email", id: "su-boltemail", phase: "Value Creation", from: { name: "Ray Whitfield", role: "Founder, Summit Comfort" }, subject: "A bolt-on target — CoolBreeze",
      body: ["CoolBreeze is a smaller rival across town - solid techs, loyal customers, owner's retiring. Exactly the kind of shop we fold in.", "They sell for around 4-5× profit. Inside Summit, that profit is worth almost double. Want me to set up a call?"], cta: "Negotiate the bolt-on" },
    { kind: "negotiation", id: "su-bolt", phase: "Value Creation",
      neg: { id: "su-bolt", title: "Bolt-on — buy CoolBreeze cheap", counterparty: "Ada Cole", role: "Owner, CoolBreeze", youWant: "low", unit: "×", start: 5, floor: 3.8, resultVar: "boltOnMult",
        intro: ["CoolBreeze's owner is retiring and wants a good home for her crew.", "\"I'd take a fair price and know my people are safe,\" Ada says."],
        rounds: [
          { theirLine: "\"I was told 5× is normal for a shop like mine.\"",
            choices: [
              { text: "Offer 4× and promise every tech keeps their job", reply: "\"...that's the deal-maker for me. My crew matters most.\"", move: 0.8, rel: 5, points: 2, feedback: "Small-shop owners sell to whoever protects their people. Fair price + job security wins." },
              { text: "Agree to 5× to be quick", reply: "\"Wonderful, thank you.\"", move: 0.2, rel: 2, points: 1, feedback: "Paying full price kills the multiple arbitrage that makes bolt-ons worth it." },
              { text: "Offer 2.5× - she has no other buyers", reply: "\"That's not fair. I'll wait for someone decent.\"", move: 0.1, rel: -7, points: 0, feedback: "Squeezing a retiree who just wants fairness loses the deal and your reputation among owners." },
            ] },
          { theirLine: "\"Nearly there — reassure me and we're done.\"",
            choices: [
              { text: "Keep her shop name for a year during handover", reply: "\"That's thoughtful. You've got a deal.\"", move: 0.6, rel: 5, points: 2, feedback: "A soft handover keeps CoolBreeze's customers - the value you're buying." },
              { text: "Nudge the price up to finish", reply: "\"Kind of you.\"", move: 0.4, rel: 2, points: 1, feedback: "Fine, but each extra turn erodes the arbitrage." },
              { text: "Rush her to sign today", reply: "\"Why the pressure? Let me think.\"", move: 0.1, rel: -4, points: 0, feedback: "Pressuring a nervous seller stalls a friendly deal." },
            ] },
        ] } },
    { kind: "decision", id: "su-integrate", phase: "Value Creation", situation: ["You've bought CoolBreeze and two more shops. Now the make-or-break step of any roll-up."],
      question: "How do you handle the bolt-ons?",
      choices: [
        { text: "Integrate them - one brand, one system, shared dispatch", points: 2, feedback: "Integration IS the value. Combined buying, scheduling and back-office turn many small shops into one strong company.", effect: { buildQuality: 9, score: 1 } },
        { text: "Let each run totally separately", points: 0, feedback: "Un-integrated, they're just a pile of small companies - you captured none of the savings you paid for.", effect: { buildQuality: -6 } },
        { text: "Rip out all their staff and rebuild", points: 1, feedback: "You bought them for their techs and customers. Gutting them destroys what you paid for.", effect: { buildQuality: -2 } },
      ] },
    { kind: "email", id: "su-exit", phase: "Exit", from: { name: "Marcus Lin", role: "Harbor Point Advisors" }, subject: "The platform is ready to sell",
      body: ["Summit is now a regional giant - 14 shops folded into one clean brand, profit up sharply. Bigger funds and a national player are circling.", "This is when the multiple arbitrage pays off. Let's sell."], cta: "Run the exit" },
    { kind: "negotiation", id: "su-exit-neg", phase: "Exit",
      neg: { id: "su-exit", title: "The exit — sell the scaled platform", counterparty: "Apex Home Services", role: "National buyer's M&A head", youWant: "high", unit: "×", start: 7, floor: 9.5, resultVar: "exitMultiple",
        intro: ["A national services company wants your scaled platform.", "\"Impressive build. We're thinking 7×,\" their head of M&A opens."],
        rounds: [
          { theirLine: "\"7× is strong for home services.\"",
            choices: [
              { text: "Price it on scale, systems, and clean integration", reply: "\"...a platform this clean is rare. It's worth more to us. Higher.\"", move: 1.5, rel: 5, points: 2, feedback: "Scale and integration are exactly what a big buyer pays up for. Sell the build." },
              { text: "Ask for slightly more, no reason", reply: "\"We can move a little.\"", move: 0.5, rel: 2, points: 1, feedback: "No rationale, small move. Anchor with the value story." },
              { text: "Demand a wild number instantly", reply: "\"That's not serious.\"", move: 0.1, rel: -7, points: 0, feedback: "Ambition needs evidence, or they walk." },
            ] },
          { theirLine: "\"Convince us to stretch to the top.\"",
            choices: [
              { text: "Remind them a rival PE fund is also bidding", reply: "\"...we won't lose it to a financial buyer. Top of range.\"", move: 1.3, rel: 4, points: 2, feedback: "Competition is the seller's superpower - it turns fair into full." },
              { text: "Take the current number", reply: "\"Certainty - smart.\"", move: 0, rel: 3, points: 1, feedback: "Fine, but you had a live rival and a push left." },
              { text: "Bluff a fake bid", reply: "\"We checked - it's not real.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff wrecks your credibility and price." },
            ] },
        ] } },
    { kind: "milestone", id: "su-exit-done", phase: "Exit", variant: "exit", title: "Exited — the roll-up delivers",
      body: ["Fourteen small shops, combined and cleaned up, sell as one big platform at a premium multiple. Ray's rollover makes him wealthy again.", "Diane: \"Multiple arbitrage, executed. Textbook.\""] },
  ],
}

/* ═══════════════ 4 · CARVE-OUT — SnackWorks ═══════════════ */
const carveout: Deal = {
  id: "snackworks", company: "SnackWorks", strategy: "Carve-out", sector: "Packaged foods",
  tagline: "A giant food conglomerate is shedding a division — buy the orphan and set it free.", difficulty: "Advanced", emoji: "📦",
  initVars: { ebitda: 12, leverageMult: 4, holdYears: 4 },
  steps: [
    { kind: "email", id: "sw-intro", phase: "Onboarding", from: DIANE, subject: "A carve-out from Titan Foods",
      body: ["Titan Foods, a huge conglomerate, is selling SnackWorks - a solid pretzel-and-cracker division that no longer fits their strategy. It's an orphan inside a giant.",
        "Carve-outs are tricky: the division shares Titan's systems, HR, and factories, so you have to build a standalone company from scratch. But orphans are cheap and often full of upside once free. Take it on?"],
      cta: "Dig in" },
    { kind: "document", id: "sw-cim", phase: "Sourcing", title: "SnackWorks — carve-out profile", subtitle: "Non-core division of Titan Foods",
      rows: [{ k: "Products", v: "Pretzels, crackers, cheese snacks" }, { k: "Revenue", v: "$140M" }, { k: "EBITDA", v: "$12M (neglected inside Titan)" }, { k: "Status", v: "Shares Titan's systems, HR, one plant" }, { k: "Why sold", v: "Too small to matter to Titan" }],
      highlights: ["Good brands starved of attention and investment", "Freed from corporate overhead, margins can jump", "Management is eager to run their own show"],
      risks: ["Must stand up its own systems, HR, and finance", "'Stranded costs' if you don't cut the corporate overhead", "Needs a transition deal (TSA) with Titan"],
      cta: "Close the profile" },
    { kind: "decision", id: "sw-fit", phase: "Sourcing", situation: ["Why can a neglected orphan make money once carved out? Diane wants the thesis."],
      question: "Where's the upside in a carve-out?",
      choices: [
        { text: "Freed from a giant's overhead, a focused team can thrive", points: 2, rel: 2, feedback: "Orphan divisions are starved of attention. Independence plus focus is where carve-out returns come from.", effect: { buildQuality: 4 } },
        { text: "There's none - if Titan didn't want it, why would we?", points: 0, feedback: "Titan sold it because it's small to THEM, not bad. What's a rounding error to a giant can be a great standalone." },
        { text: "Only the brand name has any value", points: 1, feedback: "The brands help, but the real prize is the margin unlocked by cutting corporate bloat and investing." },
      ] },
    { kind: "decision", id: "sw-structure", phase: "Negotiation", from: DIANE, subject: "Structure the carve-out",
      situation: ["You'll spend real money building standalone systems in year one. Don't over-lever into that cost."],
      question: "How do you structure it?",
      choices: [
        { text: "Moderate debt, with cash reserved for the stand-up costs", points: 2, feedback: "Carve-outs cost money to separate. Keep cash for that build, or you strangle the new company at birth.", effect: { leverageMult: 4 } },
        { text: "Max leverage - it's a stable food business", points: 1, feedback: "Stable, but the one-time separation costs are large. Over-levering leaves nothing to fund the stand-up.", effect: { leverageMult: 5.5 } },
        { text: "No debt, pay all cash", points: 1, feedback: "Safe but muted returns. Some leverage was fine given the steady cash flow.", effect: { leverageMult: 1.5 } },
      ] },
    { kind: "negotiation", id: "sw-loi", phase: "Negotiation",
      neg: { id: "sw-loi", title: "The LOI — negotiate with a giant", counterparty: "Vincent Osei", role: "Head of M&A, Titan Foods", youWant: "low", unit: "×", start: 8, floor: 6.5, resultVar: "entryMultiple",
        intro: ["Titan's corporate M&A team is polished and unsentimental - no founder emotions here, just process.", "Vincent: \"We want a clean, certain exit. Our screens say 8×. Make your case.\""],
        rounds: [
          { theirLine: "\"8× is our internal mark.\"",
            choices: [
              { text: "Offer 6.6×, pricing in the carve-out complexity", reply: "\"...the separation costs are a fair point. There's room to move.\"", move: 1, rel: 4, points: 2, feedback: "With a corporate seller, the carve-out complexity IS your leverage. Price the messiness in." },
              { text: "Split to 7.5× to seem cooperative", reply: "\"Reasonable - we can likely accept.\"", move: 0.3, rel: 2, points: 1, feedback: "Corporate sellers happily take a high offer. Anchor on the real complexity." },
              { text: "Lowball 4.5× and nitpick everything", reply: "\"We have other buyers. This isn't productive.\"", move: 0.1, rel: -6, points: 0, feedback: "A giant with options won't tolerate a lowball tantrum." },
            ] },
          { theirLine: "\"Close the gap and offer us certainty.\"",
            choices: [
              { text: "Offer speed and a fair transition-services deal", reply: "\"Certainty and a clean TSA - that's what we want. Done.\"", move: 1, rel: 5, points: 2, feedback: "Corporates value certainty and a smooth separation over the last dollar. That's your close." },
              { text: "Just raise your price", reply: "\"We'll take it.\"", move: 0.5, rel: 2, points: 1, feedback: "Paying up works, but you gave away entry value you didn't need to." },
              { text: "Stall to grind them down", reply: "\"We'll move to the next bidder, then.\"", move: 0.1, rel: -6, points: 0, feedback: "Corporates run processes on a clock - stalling loses the deal." },
            ] },
        ] } },
    { kind: "decision", id: "sw-tsa", phase: "Financing", subject: "The transition deal (TSA)",
      situation: ["For 12 months, Titan will run some systems for you while you build your own. How do you approach this handover?"],
      question: "What's your TSA plan?",
      choices: [
        { text: "A clear TSA now, and hire to stand up systems fast", points: 2, feedback: "A defined transition plus urgency to go independent avoids being stuck paying a giant for slow service.", effect: { buildQuality: 5, score: 1 } },
        { text: "Lean on Titan's systems indefinitely - it's easy", points: 0, feedback: "TSAs get expensive and Titan has no reason to help forever. Dependence on the old parent is a trap.", effect: { buildQuality: -5 } },
        { text: "Cut all ties on day one, no transition", points: 1, feedback: "Ripping the cord instantly risks broken payroll and orders. A short, planned handover is the pro move." },
      ] },
    { kind: "milestone", id: "sw-closed", phase: "Closing", variant: "closed", title: "Carved out — a company is born",
      body: ["SnackWorks is independent for the first time in decades. The team is thrilled to run their own show - now make it a real company."] },
    { kind: "decision", id: "sw-v1", phase: "Value Creation", situation: ["Freed from Titan, the biggest lever appears immediately."],
      question: "Your first value move?",
      choices: [
        { text: "Cut the corporate overhead Titan was charging", points: 2, feedback: "Carve-outs often carry bloated 'corporate allocations'. Cutting them is instant, real margin.", effect: { buildQuality: 8, score: 1 } },
        { text: "Keep spending like a big-company division", points: 0, feedback: "You bought freedom from that bloat - keeping it wastes the whole thesis.", effect: { buildQuality: -5 } },
        { text: "Immediately launch ten new products", points: 1, feedback: "Innovation later - first stand up the company and capture the easy overhead savings.", effect: { buildQuality: 1 } },
      ] },
    { kind: "decision", id: "sw-v2", phase: "Value Creation", situation: ["Standalone and leaner, the team wants to invest the freed-up cash in growth."],
      question: "Where do you invest?",
      choices: [
        { text: "Fund the products the team was never allowed to build", points: 2, feedback: "Neglected divisions are full of good ideas starved of capital. Backing them is the growth payoff.", effect: { buildQuality: 7, score: 1 } },
        { text: "Sit on the cash to be safe", points: 1, feedback: "Playing it too safe wastes the newly focused team's momentum.", effect: { buildQuality: -1 } },
        { text: "Chase a splashy, unrelated acquisition", points: 0, feedback: "You just gained focus - don't blow it on a shiny, off-strategy deal.", effect: { buildQuality: -4 } },
      ] },
    { kind: "email", id: "sw-exit", phase: "Exit", from: { name: "Marcus Lin", role: "Harbor Point Advisors" }, subject: "The orphan is now a prize",
      body: ["Free of Titan's overhead and finally investing in itself, SnackWorks has grown into a sharp, profitable independent. Strategics love a clean, standalone brand.", "Let's sell the company you built."], cta: "Run the exit" },
    { kind: "negotiation", id: "sw-exit-neg", phase: "Exit",
      neg: { id: "sw-exit", title: "The exit — sell the standalone", counterparty: "Global Foods Inc.", role: "Strategic buyer", youWant: "high", unit: "×", start: 7, floor: 9, resultVar: "exitMultiple",
        intro: ["A strategic food buyer wants your clean, independent SnackWorks.", "\"A nice standalone. We're at 7×,\" their team offers."],
        rounds: [
          { theirLine: "\"7× is a full price for packaged snacks.\"",
            choices: [
              { text: "Show the margin turnaround and the growth", reply: "\"...the margin story is real. Worth more than a standalone screen. Higher.\"", move: 1.3, rel: 5, points: 2, feedback: "You transformed a neglected orphan - price it on that transformation." },
              { text: "Ask vaguely for more", reply: "\"Small move, sure.\"", move: 0.4, rel: 2, points: 1, feedback: "Vague ask, small move." },
              { text: "Demand a huge jump instantly", reply: "\"Not serious.\"", move: 0.1, rel: -7, points: 0, feedback: "No basis, no deal." },
            ] },
          { theirLine: "\"Give us a reason for our top number.\"",
            choices: [
              { text: "Note a rival strategic is also circling", reply: "\"...we'll pay up to win it.\"", move: 1.2, rel: 4, points: 2, feedback: "Competition lifts the price to full value." },
              { text: "Take the current number", reply: "\"Certainty, smart.\"", move: 0, rel: 3, points: 1, feedback: "Fine, but you had a push left." },
              { text: "Bluff a fake bid", reply: "\"We checked - false.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff kills your price." },
            ] },
        ] } },
    { kind: "milestone", id: "sw-exit-done", phase: "Exit", variant: "exit", title: "Exited — the orphan pays off",
      body: ["The division nobody at Titan wanted sells as a thriving independent brand. The team that finally got to run it did brilliantly.", "Diane: \"You saw the company hiding inside the conglomerate. That's the skill.\""] },
  ],
}

/* ═══════════════ 5 · TAKE-PRIVATE — Lumen Fitness ═══════════════ */
const takePrivate: Deal = {
  id: "lumen", company: "Lumen Fitness", strategy: "Take-private", sector: "Public gym chain",
  tagline: "A struggling small public company — buy it off the stock market and fix it in private.", difficulty: "Advanced", emoji: "🏋️",
  initVars: { ebitda: 20, leverageMult: 4.5, holdYears: 4 },
  steps: [
    { kind: "email", id: "lu-intro", phase: "Onboarding", from: DIANE, subject: "A take-private opportunity",
      body: ["Lumen Fitness is a small public gym chain whose stock has slumped - the market's punishing it, but the business is fine and undervalued.",
        "Taking a public company private means paying a premium over its share price, winning over the board, and getting shareholders to vote yes. Then you fix it away from quarterly pressure. High-profile, high-stakes. Want it?"],
      cta: "Study Lumen" },
    { kind: "document", id: "lu-cim", phase: "Sourcing", title: "Lumen Fitness — public filing summary", subtitle: "Small-cap gym chain · take-private target",
      rows: [{ k: "Locations", v: "140 gyms" }, { k: "Revenue", v: "$260M" }, { k: "EBITDA", v: "$20M" }, { k: "Stock", v: "Down 45% this year" }, { k: "Trades at", v: "~7× profit (peers at 10×)" }],
      highlights: ["Solid membership base, undervalued by the market", "No quarterly pressure once private = room to invest", "Cheap versus fitness peers"],
      risks: ["Must pay a premium and win a shareholder vote", "A rival bidder could top your offer", "Public deals are slow and very visible"],
      cta: "Close the summary" },
    { kind: "decision", id: "lu-fit", phase: "Sourcing", situation: ["Why take a public company private? Diane wants the logic."],
      question: "What's the case for taking Lumen private?",
      choices: [
        { text: "It's cheap, and privacy lets us fix it without quarterly pressure", points: 2, rel: 2, feedback: "A beaten-down but sound public company is a classic take-private: undervalued, and freer to fix in private.", effect: { buildQuality: 4 } },
        { text: "Public companies are always overpriced - skip it", points: 0, feedback: "This one trades BELOW its peers. The market's pessimism is exactly the opportunity." },
        { text: "Only to flip the shares for a quick pop", points: 1, feedback: "Take-privates aren't day-trades. The value comes from years of fixing it in private." },
      ] },
    { kind: "decision", id: "lu-premium", phase: "Negotiation", from: DIANE, subject: "What premium do we offer?",
      situation: ["Lumen trades at 7× profit. To win a public company you must pay a premium over the market price - but overpay and the returns vanish."],
      question: "Your opening offer to the board?",
      choices: [
        { text: "A fair premium to ~8.5×, backed by peer valuations", points: 2, feedback: "Enough of a premium to be taken seriously, anchored to what peers are worth. Credible and disciplined.", effect: { buildQuality: 3, score: 1 } },
        { text: "A tiny premium - barely above the stock price", points: 1, feedback: "A stingy premium gets rejected by the board and shareholders. You must pay to take control." },
        { text: "A massive premium to guarantee the win", points: 0, feedback: "Overpaying to 'win' a public deal is exactly how take-privates lose money.", effect: { buildQuality: -3 } },
      ] },
    { kind: "negotiation", id: "lu-loi", phase: "Negotiation",
      neg: { id: "lu-loi", title: "The board — agree a price", counterparty: "Eleanor Voss", role: "Chair of Lumen's board", youWant: "low", unit: "×", start: 9.5, floor: 8, resultVar: "entryMultiple",
        intro: ["Lumen's board must get the best deal for shareholders - and avoid getting sued.", "Eleanor: \"Our bankers say the company's worth 9.5× to a buyer. Convince us to recommend you.\""],
        rounds: [
          { theirLine: "\"9.5× is our fair-value view.\"",
            choices: [
              { text: "Anchor at 8.2× on the peer multiples and the slump", reply: "\"...the peer comps are fair, and the stock has struggled. There's room.\"", move: 0.8, rel: 4, points: 2, feedback: "A board answers to data and shareholders - argue the comps, not emotion." },
              { text: "Split to 9× quickly", reply: "\"That's close to our mark - easy to recommend.\"", move: 0.2, rel: 2, points: 1, feedback: "Boards happily take a rich offer. Anchor lower on the comps." },
              { text: "Threaten a hostile bid over their heads", reply: "\"Then we'll fight you, and shareholders will notice.\"", move: 0.1, rel: -7, points: 0, feedback: "Going hostile early turns the board against you and drags in lawyers." },
            ] },
          { theirLine: "\"Give us cover to recommend you to shareholders.\"",
            choices: [
              { text: "Offer a 'go-shop' so they can check for better bids", reply: "\"That protects us and shareholders. We can recommend this.\"", move: 0.7, rel: 5, points: 2, feedback: "A go-shop gives the board legal cover and confidence - a savvy, deal-closing concession." },
              { text: "Just raise the price", reply: "\"We'll take it.\"", move: 0.4, rel: 2, points: 1, feedback: "Paying up works but costs you entry value." },
              { text: "Pressure them to decide tonight", reply: "\"Boards don't rush multi-million-dollar votes.\"", move: 0.1, rel: -5, points: 0, feedback: "Rushing a public board just looks reckless." },
            ] },
        ] } },
    { kind: "decision", id: "lu-topping", phase: "Diligence", subject: "A rival bid appears",
      situation: ["During the go-shop, a rival PE fund lobs in a slightly higher bid. The board asks if you'll top it. Your models say your original price was already full."],
      question: "How do you respond?",
      choices: [
        { text: "Nudge up modestly to your walk-away, then hold firm", points: 2, feedback: "Defend the deal to a disciplined limit, then stop. Winning a bidding war by overpaying is losing.", effect: { buildQuality: 2, score: 1 } },
        { text: "Blow past your limit to win at any cost", points: 0, feedback: "Overpaying to beat a rival is the 'winner's curse' - you win the company and lose the return.", effect: { buildQuality: -4 } },
        { text: "Walk away instantly the moment they bid", points: 1, feedback: "Too hasty - a small, disciplined bump was fine. Fold only if the price crosses your real limit." },
      ] },
    { kind: "milestone", id: "lu-closed", phase: "Closing", variant: "closed", title: "Taken private — Lumen is yours",
      body: ["Shareholders vote yes. Lumen delists from the stock market and is now private - free of quarterly noise, and yours to fix."] },
    { kind: "decision", id: "lu-v1", phase: "Value Creation", situation: ["Away from the quarterly spotlight, you can finally make moves the public market punished."],
      question: "Your first private move?",
      choices: [
        { text: "Invest in tired gyms and new equipment for the long term", points: 2, feedback: "Public markets punished this spending; in private you can invest for members and years, not quarters.", effect: { buildQuality: 8, score: 1 } },
        { text: "Slash all spending to pump this year's profit", points: 0, feedback: "Starving the gyms drives members away. Take-privates win by investing, not by cutting to the bone.", effect: { buildQuality: -6 } },
        { text: "Do nothing different than before", points: 1, feedback: "If nothing changes, why did you take it private? The freedom to act is the whole point.", effect: { buildQuality: -2 } },
      ] },
    { kind: "decision", id: "lu-v2", phase: "Value Creation", subject: "Memberships are climbing",
      situation: ["The refreshed gyms are winning members back. You can push growth further."],
      question: "How do you grow?",
      choices: [
        { text: "Add a digital app and open gyms in strong markets", points: 2, feedback: "Grow where you're winning and add recurring digital revenue - disciplined expansion compounds the fix.", effect: { buildQuality: 7, score: 1 } },
        { text: "Open everywhere at once, fast", points: 1, feedback: "Undisciplined expansion outruns your ability to run it well. Grow where it works first.", effect: { buildQuality: -2 } },
        { text: "Raise prices sharply to cash in", points: 0, feedback: "Gouging members you just won back sends them straight to the cheaper rival.", effect: { buildQuality: -4 } },
      ] },
    { kind: "email", id: "lu-exit", phase: "Exit", from: { name: "Marcus Lin", role: "Harbor Point Advisors" }, subject: "Time to sell — or re-list",
      body: ["Lumen is thriving: members up, profit up, gyms refreshed. You could sell to a strategic or even take it public again at a much higher value.", "The market that punished it will pay up for it now. Let's exit."], cta: "Run the exit" },
    { kind: "negotiation", id: "lu-exit-neg", phase: "Exit",
      neg: { id: "lu-exit", title: "The exit — sell the fixed company", counterparty: "FitGroup Global", role: "Strategic buyer", youWant: "high", unit: "×", start: 8, floor: 10.5, resultVar: "exitMultiple",
        intro: ["A global fitness strategic wants your revitalized chain.", "\"Nice turnaround. We're at 8×,\" they open."],
        rounds: [
          { theirLine: "\"8× reflects a solid gym business.\"",
            choices: [
              { text: "Show the member growth and premium peers", reply: "\"...the growth is real, and peers trade higher. Let's move up.\"", move: 1.5, rel: 5, points: 2, feedback: "Price it on momentum and where healthy peers trade - not on where it was." },
              { text: "Ask for a little more, vaguely", reply: "\"Small nudge, fine.\"", move: 0.5, rel: 2, points: 1, feedback: "Vague ask, small move." },
              { text: "Demand a huge jump now", reply: "\"That's not real.\"", move: 0.1, rel: -7, points: 0, feedback: "No basis, they walk." },
            ] },
          { theirLine: "\"Justify our top number.\"",
            choices: [
              { text: "Note you could just re-IPO it instead", reply: "\"...a public listing would price it high. Okay, top of range.\"", move: 1.3, rel: 4, points: 2, feedback: "A credible alternative exit (re-IPO) is real leverage that lifts the price." },
              { text: "Take the number", reply: "\"Certainty, smart.\"", move: 0, rel: 3, points: 1, feedback: "Fine, but you had leverage left." },
              { text: "Bluff a fake buyer", reply: "\"We checked - false.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff kills your price." },
            ] },
        ] } },
    { kind: "milestone", id: "lu-exit-done", phase: "Exit", variant: "exit", title: "Exited — the market pays up",
      body: ["The company the stock market gave up on sells for far more than you paid to take it private. Fixed away from the quarterly glare, it shines again.", "Diane: \"You bought pessimism and sold results. Beautiful.\""] },
  ],
}

/* ═══════════════ 6 · GROWTH EQUITY — BrightBox ═══════════════ */
const growth: Deal = {
  id: "brightbox", company: "BrightBox", strategy: "Growth equity", sector: "DTC home goods",
  tagline: "A rocket-ship online brand doesn't need your control — just your capital and a fair deal.", difficulty: "Core", emoji: "🚀",
  initVars: { ebitda: 5, leverageMult: 0, holdYears: 4 },
  steps: [
    { kind: "email", id: "bb-intro", phase: "Onboarding", from: DIANE, subject: "A growth-equity deal — different rules",
      body: ["BrightBox sells beautiful home goods online and is growing 50% a year. The founder, Priya Nair, isn't selling control - she wants a partner and capital to grow faster.",
        "Growth equity means a MINORITY stake, no debt, and founder-friendly terms. You win by backing a rocket, not by controlling it. Ready to think differently?"],
      cta: "Meet BrightBox" },
    { kind: "document", id: "bb-cim", phase: "Sourcing", title: "BrightBox — growth investment memo", subtitle: "DTC home goods · minority round",
      rows: [{ k: "Product", v: "Design-led home goods, sold online" }, { k: "Revenue", v: "$60M, up 50%/yr" }, { k: "EBITDA", v: "$5M (reinvesting for growth)" }, { k: "Founder", v: "Priya Nair — keeps control" }, { k: "Raising", v: "Minority stake, no debt" }],
      highlights: ["Explosive, loved brand with real repeat customers", "Founder is exceptional and staying in charge", "Huge market still barely tapped"],
      risks: ["You won't have control - terms matter more than ever", "Growth could slow; the price is high", "DTC is competitive and ad costs rise"],
      cta: "Close the memo" },
    { kind: "decision", id: "bb-fit", phase: "Sourcing", situation: ["Growth equity is a different game. Diane checks your mindset."],
      question: "How do you win and profit here?",
      choices: [
        { text: "Back a great founder at a fair price on clean terms", points: 2, rel: 2, feedback: "In growth equity you bet on the founder and the growth - your return rides their success, not your control.", effect: { buildQuality: 4 } },
        { text: "Demand control or walk away", points: 0, feedback: "Great founders won't give up control, and shouldn't. Insisting on it loses the best deals." },
        { text: "Load it with debt to boost returns", points: 1, feedback: "Growth companies reinvest every dollar - piling on debt would starve the growth you're buying." },
      ] },
    { kind: "decision", id: "bb-terms", phase: "Negotiation", from: DIANE, subject: "Terms, not control",
      situation: ["Without control, your protection comes from the TERMS. What do you prioritize?"],
      question: "What terms do you push for?",
      choices: [
        { text: "A board seat and a few key protections, kept founder-friendly", points: 2, feedback: "Reasonable governance rights protect you without smothering the founder - the growth-equity sweet spot.", effect: { buildQuality: 3, score: 1 } },
        { text: "Heavy control terms and vetoes over everything", points: 0, feedback: "Overreaching on terms signals distrust and drives great founders to a friendlier investor.", effect: { buildQuality: -3 } },
        { text: "No terms at all - just hand over the money", points: 1, feedback: "Zero protection on a minority stake is naive. A little governance is just prudent." },
      ] },
    { kind: "negotiation", id: "bb-loi", phase: "Negotiation",
      neg: { id: "bb-loi", title: "The round — agree a valuation", counterparty: "Priya Nair", role: "Founder & CEO, BrightBox", youWant: "low", unit: "×", start: 12, floor: 9, resultVar: "entryMultiple",
        intro: ["Priya has other investors interested - she'll pick a partner, not just a check.", "\"I want a fair price and a partner who gets it,\" she says. \"Other funds are circling. Where are you?\""],
        rounds: [
          { theirLine: "\"I think we're worth 12× - look at the growth.\"",
            choices: [
              { text: "Offer 9.5×, backed by growth-stage comps", reply: "\"...that's grounded, and I like how you think. Let's talk.\"", move: 1.7, rel: 5, points: 2, feedback: "Even for a rocket, price it on comparable growth deals - a fair, defensible number." },
              { text: "Meet her 12× to win the deal", reply: "\"Great, you're in!\" - but you paid a rich price.", move: 0.3, rel: 3, points: 1, feedback: "Overpaying to win a hot round is the 'winner's curse'. A fair price protects your MOIC." },
              { text: "Lowball at 6× - she has no profit", points: 0, reply: "\"You don't understand growth. Pass.\"", move: 0.1, rel: -8, feedback: "Lowballing a great founder on a growth deal just loses it to a smarter fund." },
            ] },
          { theirLine: "\"Close it, and show me you're the right partner.\"",
            choices: [
              { text: "Offer real help: hiring, supply chain, next raise", reply: "\"That's exactly what I need. You're my partner.\"", move: 1.4, rel: 6, points: 2, feedback: "Founders pick partners, not prices. Concrete help wins hot rounds and bridges the gap." },
              { text: "Just raise your price further", reply: "\"Sure, I'll take the higher number.\"", move: 0.6, rel: 2, points: 1, feedback: "Paying more wins it but caps your return - and she wanted a partner, not a checkbook." },
              { text: "Give her an exploding 24-hour offer", reply: "\"Pressure tactics? That's a no from me.\"", move: 0.1, rel: -7, points: 0, feedback: "Exploding offers on great founders backfire - reputation travels." },
            ] },
        ] } },
    { kind: "milestone", id: "bb-closed", phase: "Closing", variant: "closed", title: "Invested — you're on the rocket",
      body: ["You've got your stake and a board seat. No control, no debt - your job now is to help Priya go even faster."] },
    { kind: "decision", id: "bb-v1", phase: "Value Creation", situation: ["Priya asks for your help. As a minority partner, where do you add the most value?"],
      question: "How do you help BrightBox grow?",
      choices: [
        { text: "Open your network: great hires, suppliers, and advice", points: 2, feedback: "A growth investor's value is their rolodex and judgment, not orders. Help her scale what works.", effect: { buildQuality: 8, score: 1 } },
        { text: "Override her decisions with your own", points: 0, feedback: "You don't have control and shouldn't act like it. Steamrolling a great founder destroys the partnership.", effect: { buildQuality: -6 } },
        { text: "Stay hands-off and just watch", points: 1, feedback: "Passive money leaves value on the table. Growth investors earn their return by genuinely helping.", effect: { buildQuality: -1 } },
      ] },
    { kind: "decision", id: "bb-v2", phase: "Value Creation", subject: "Growth is slowing a little",
      situation: ["Ad costs are rising and growth cooled from 50% to 30%. Priya wants to spend big to reaccelerate."],
      question: "Your advice?",
      choices: [
        { text: "Prove new channels pay back before pouring money in", points: 2, feedback: "Disciplined growth: find the engine, then fund it. Spending into rising ad costs blindly burns cash.", effect: { buildQuality: 7, score: 1 } },
        { text: "Spend everything on ads to force growth back up", points: 0, feedback: "Flooring ad spend as costs rise is the classic DTC flameout. Growth you can't sustain isn't growth.", effect: { buildQuality: -5 } },
        { text: "Slam the brakes and stop all growth spend", points: 1, feedback: "Too timid - a growth company that stops investing gets lapped. The answer is disciplined spend, not zero." },
      ] },
    { kind: "email", id: "bb-exit", phase: "Exit", from: { name: "Priya Nair", role: "Founder & CEO, BrightBox" }, subject: "A big offer just came in",
      body: ["A retail giant wants to buy BrightBox, and a late-stage fund wants to lead a big new round at a huge valuation. Either way, your stake is worth a fortune now.", "You backed me when it counted. Let's talk about the exit together."], cta: "Discuss the exit" },
    { kind: "negotiation", id: "bb-exit-neg", phase: "Exit",
      neg: { id: "bb-exit", title: "The exit — sell your stake high", counterparty: "MegaRetail Corp.", role: "Acquirer's corp-dev lead", youWant: "high", unit: "×", start: 10, floor: 14, resultVar: "exitMultiple",
        intro: ["A retail giant is buying BrightBox; you're negotiating the value of your stake.", "\"It's a lovely brand. We value it at 10×,\" their lead says."],
        rounds: [
          { theirLine: "\"10× is generous for a DTC brand.\"",
            choices: [
              { text: "Show the repeat-customer loyalty and growth runway", reply: "\"...the loyalty metrics are exceptional. It's worth more. Higher.\"", move: 1.8, rel: 5, points: 2, feedback: "Great DTC brands are priced on loyalty and runway - make them see the future value." },
              { text: "Ask for a bit more, no reason", reply: "\"Small move, fine.\"", move: 0.6, rel: 2, points: 1, feedback: "Anchor to a metric, not a vibe." },
              { text: "Demand triple immediately", reply: "\"That's fantasy.\"", move: 0.1, rel: -7, points: 0, feedback: "No basis, no deal." },
            ] },
          { theirLine: "\"Give us a reason for our top price.\"",
            choices: [
              { text: "Note the late-stage fund would fund it instead", reply: "\"...a fresh round would price it high. Okay, top of range.\"", move: 1.5, rel: 4, points: 2, feedback: "A live alternative (staying private, funded) is real leverage." },
              { text: "Take the current number", reply: "\"Certainty, smart.\"", move: 0, rel: 3, points: 1, feedback: "Fine, but you had leverage left." },
              { text: "Bluff a fake bidder", reply: "\"We'd know. False.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff wrecks the price." },
            ] },
        ] } },
    { kind: "milestone", id: "bb-exit-done", phase: "Exit", variant: "exit", title: "Exited — the rocket paid off",
      body: ["BrightBox sells to a retail giant, and your minority stake returns a fortune. Priya thanks you for being the partner who helped, not the boss who meddled.", "Diane: \"No control, no leverage - and a great return. You backed the right founder.\""] },
  ],
}

/* ═══════════════ 7 · FAMILY SUCCESSION — Harborline Boats ═══════════════ */
const family: Deal = {
  id: "harborline", company: "Harborline Boats", strategy: "Family succession", sector: "Boat manufacturing",
  tagline: "Three generations, one factory town, a divided family — buy it without breaking it.", difficulty: "Core", emoji: "⛵",
  initVars: { ebitda: 7, leverageMult: 3.5, holdYears: 5 },
  steps: [
    { kind: "email", id: "hl-intro", phase: "Onboarding", from: DIANE, subject: "A family business at a crossroads",
      body: ["Harborline Boats has built beloved sailboats for 70 years - third generation now, and the family is split on selling. It's the pride of its little factory town.",
        "Family deals are as much about people and legacy as numbers: earnouts, keeping the name, protecting the workers. Handle it with care and it's a gem. Interested?"],
      cta: "Learn the story" },
    { kind: "document", id: "hl-cim", phase: "Sourcing", title: "Harborline Boats — family profile", subtitle: "3rd-generation boat maker · succession sale",
      rows: [{ k: "Product", v: "Premium sailboats, 70-year heritage" }, { k: "Revenue", v: "$70M" }, { k: "EBITDA", v: "$7M" }, { k: "Owners", v: "The Halloran family (divided)" }, { k: "Town", v: "Largest employer in Port Halloran" }],
      highlights: ["Iconic brand with a waiting list of buyers", "Craftsmen with decades of skill", "Never modernized — big efficiency upside"],
      risks: ["Family disagrees about selling", "The town watches every move", "Old factory, manual processes"],
      cta: "Close the profile" },
    { kind: "meeting", id: "hl-mtg", phase: "Diligence", person: { name: "Tom Halloran", role: "3rd-gen owner, Harborline" }, pickCount: 3,
      intro: ["Tom wants to sell and retire; his sister Kate is wary. You meet Tom at the dock. Choose your three questions with care."],
      questions: [
        { q: "What would make this feel right for your family?", a: "\"Keep the Harborline name and don't move the factory out of town. That's everything to us.\"", key: true },
        { q: "Where's the biggest room to improve the business?", a: "\"We've never modernized. Same processes as my grandfather. A pro could lift margins a lot.\"", key: true },
        { q: "How do we win your sister Kate over?", a: "\"Show her you'll protect the workers. She grew up with these people. That's her line.\"", key: true },
        { q: "What's your favorite boat you've built?", a: "\"The '38 cruiser. But that's nostalgia, not diligence.\"", key: false },
        { q: "How old is the office building?", a: "\"Ancient and charming. Not your concern.\"", key: false },
        { q: "Do you have a company logo I can see?", a: "\"On every transom for 70 years. Irrelevant to your model.\"", key: false },
      ] },
    { kind: "decision", id: "hl-structure", phase: "Negotiation", from: DIANE, subject: "Structure with the family in mind",
      situation: ["A heritage brand and a watching town argue for stability, not aggressive debt."],
      question: "How do you structure it?",
      choices: [
        { text: "Modest debt - protect a heritage brand and its town", points: 2, feedback: "A conservative structure keeps the business (and the community's trust) safe through any bumps.", effect: { leverageMult: 3 } },
        { text: "Max leverage to boost your return", points: 1, feedback: "Loading debt on a slow-and-steady craftsman business risks the very stability that makes it valuable.", effect: { leverageMult: 5 } },
        { text: "No debt, all equity", points: 1, feedback: "Safe, but a little leverage was fine for a steady, profitable maker. Muted returns otherwise.", effect: { leverageMult: 1 } },
      ] },
    { kind: "negotiation", id: "hl-loi", phase: "Negotiation",
      neg: { id: "hl-loi", title: "The LOI — win the family", counterparty: "Kate Halloran", role: "Co-owner (the wary one)", youWant: "low", unit: "×", start: 7, floor: 5.5, resultVar: "entryMultiple",
        intro: ["Tom's ready to sell; Kate holds the swing vote and cares about the people.", "Kate: \"I'll only sign if I trust the buyer. And we won't be lowballed on something we built. Convince me.\""],
        rounds: [
          { theirLine: "\"We think it's worth 7×. And the workers come first.\"",
            choices: [
              { text: "Offer 5.7× and guarantee no factory moves or layoffs", reply: "\"...the guarantee matters to me more than the last half-turn. Keep talking.\"", move: 0.9, rel: 6, points: 2, feedback: "For a family seller, protecting people IS the deal. Fair price plus real commitments wins Kate." },
              { text: "Offer near 6.7× to smooth it over", reply: "\"That's kind - Tom will love it.\"", move: 0.3, rel: 3, points: 1, feedback: "Overpaying to please the family dents your return. Commitments, not extra dollars, win them." },
              { text: "Lowball 4× - old factory, old tech", reply: "\"You just insulted 70 years of work. No.\"", move: 0.1, rel: -9, points: 0, feedback: "Belittling their heritage is the fastest way to lose a family deal." },
            ] },
          { theirLine: "\"Give the family a reason to trust you with our name.\"",
            choices: [
              { text: "Keep the Harborline name and offer them a rollover", reply: "\"You'd keep our name AND stay partners? Now I'm in.\"", move: 0.9, rel: 7, points: 2, feedback: "Protecting the name and inviting them to stay invested seals a family deal - and the price gap." },
              { text: "Just raise your offer", reply: "\"We'll take the money, I suppose.\"", move: 0.5, rel: 1, points: 1, feedback: "Money alone doesn't earn a wary family's trust - and it costs you value." },
              { text: "Push them to decide now", reply: "\"This is our life's work. We won't be rushed.\"", move: 0.1, rel: -6, points: 0, feedback: "Rushing a family through an emotional sale backfires badly." },
            ] },
        ] } },
    { kind: "decision", id: "hl-signing", phase: "Closing", subject: "One last family request",
      situation: ["At signing, Tom asks that a long-time plant manager be kept on and that apprentices keep getting trained - the town's tradition."],
      question: "How do you respond?",
      choices: [
        { text: "Agree happily - that culture is an asset worth keeping", points: 2, feedback: "The craftsmanship and loyalty ARE the brand. Honoring the tradition protects your investment.", effect: { buildQuality: 3, rolloverAccepted: true, score: 1 } },
        { text: "Refuse - you want a free hand on staffing", points: 1, feedback: "A free hand sounds efficient but throws away the skilled culture and the family's goodwill." },
        { text: "Agree, but secretly plan to cut it all later", points: 0, feedback: "Breaking a promise to a family and a town destroys trust - and word travels in a tight community.", effect: { buildQuality: -4 } },
      ] },
    { kind: "milestone", id: "hl-closed", phase: "Closing", variant: "closed", title: "Deal closed — the name lives on",
      body: ["The Hallorans sign, reassured. The town breathes easy - same name, same people, new investment coming. Now modernize without losing the soul."] },
    { kind: "decision", id: "hl-v1", phase: "Value Creation", situation: ["The craftsmanship is world-class; the processes are from 1955. Where do you start?"],
      question: "Your first improvement?",
      choices: [
        { text: "Modernize production while keeping the craft quality", points: 2, feedback: "New tools in skilled hands lift output and margin without losing what makes the boats special.", effect: { buildQuality: 8, score: 1 } },
        { text: "Automate everything and replace the craftsmen", points: 0, feedback: "The handmade quality is the brand. Replacing the craftsmen destroys the premium you paid for.", effect: { buildQuality: -6 } },
        { text: "Change nothing to avoid upsetting anyone", points: 1, feedback: "Honoring tradition doesn't mean freezing in time - you bought the upside of modernizing carefully.", effect: { buildQuality: -1 } },
      ] },
    { kind: "decision", id: "hl-v2", phase: "Value Creation", subject: "Demand is strong",
      situation: ["With better efficiency, you can make more boats. The waiting list is long."],
      question: "How do you grow?",
      choices: [
        { text: "Expand the dealer network and add a new model line", points: 2, feedback: "Meet the real demand and extend the beloved brand carefully - premium growth done right.", effect: { buildQuality: 7, score: 1 } },
        { text: "Slash prices to sell far more, faster", points: 0, feedback: "Discounting a premium heritage brand cheapens it and trains buyers to wait for sales.", effect: { buildQuality: -4 } },
        { text: "Keep output flat - scarcity is nice", points: 1, feedback: "Some scarcity helps a luxury brand, but ignoring a long waitlist leaves real profit unmade." },
      ] },
    { kind: "email", id: "hl-exit", phase: "Exit", from: { name: "Marcus Lin", role: "Harbor Point Advisors" }, subject: "A marine giant wants Harborline",
      body: ["Harborline is modernized, more profitable, and still beloved - name intact, town proud. A large marine company wants to add it to their premium fleet.", "You honored the legacy and built the value. Let's sell it well."], cta: "Run the exit" },
    { kind: "negotiation", id: "hl-exit-neg", phase: "Exit",
      neg: { id: "hl-exit", title: "The exit — sell the heritage brand", counterparty: "Blue Water Marine", role: "Strategic buyer", youWant: "high", unit: "×", start: 7, floor: 9, resultVar: "exitMultiple",
        intro: ["A premium marine group wants Harborline's brand and craftsmanship.", "\"A gorgeous brand. We're at 7×,\" they open."],
        rounds: [
          { theirLine: "\"7× is fair for a boat maker.\"",
            choices: [
              { text: "Show the modernized margins and the brand's cachet", reply: "\"...the margin lift plus the heritage is special. Worth more. Higher.\"", move: 1.3, rel: 5, points: 2, feedback: "Heritage brands with fixed operations command a premium - sell both the soul and the numbers." },
              { text: "Ask for more, vaguely", reply: "\"Small move.\"", move: 0.4, rel: 2, points: 1, feedback: "Vague ask, small move." },
              { text: "Demand a huge jump now", reply: "\"Not serious.\"", move: 0.1, rel: -7, points: 0, feedback: "No basis, they walk." },
            ] },
          { theirLine: "\"Give us a reason for our best price.\"",
            choices: [
              { text: "Note another premium marque is also bidding", reply: "\"...we won't lose this brand. Top of range.\"", move: 1.2, rel: 4, points: 2, feedback: "A rival for a rare brand lifts the price to full value." },
              { text: "Take the number", reply: "\"Certainty, smart.\"", move: 0, rel: 3, points: 1, feedback: "Fine, but you had a push left." },
              { text: "Bluff a fake bid", reply: "\"We checked - false.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff kills your price." },
            ] },
        ] } },
    { kind: "milestone", id: "hl-exit-done", phase: "Exit", variant: "exit", title: "Exited — legacy honored, value built",
      body: ["Harborline joins a premium fleet with its name, its craftsmen, and its town intact - and a far bigger price than the family imagined. The Hallorans' rollover pays off.", "Diane: \"You proved you can do a deal AND keep your word. Rare and valuable.\""] },
  ],
}

/* ═══════════════ 8 · DISTRESSED — Northwind Outfitters ═══════════════ */
const distressed: Deal = {
  id: "northwind", company: "Northwind Outfitters", strategy: "Distressed / special situations", sector: "Outdoor retail",
  tagline: "An outdoor retailer on the brink of bankruptcy — buy it from the creditors and revive it.", difficulty: "Advanced", emoji: "🏔️",
  initVars: { ebitda: 2, leverageMult: 1.5, holdYears: 3 },
  steps: [
    { kind: "email", id: "nw-intro", phase: "Onboarding", from: DIANE, subject: "A distressed situation — move carefully",
      body: ["Northwind Outfitters, a well-known outdoor gear retailer, is nearly bankrupt - drowning in debt and old inventory. Its lenders just want out.",
        "Distressed deals are bought cheap from creditors, then restructured. The brand is loved; the balance sheet is a disaster. High risk, potentially huge reward. Want to try to save it?"],
      cta: "Assess the wreck" },
    { kind: "document", id: "nw-cim", phase: "Sourcing", title: "Northwind Outfitters — situation report", subtitle: "Distressed retailer · creditor-led sale",
      rows: [{ k: "Stores", v: "80 (30 unprofitable)" }, { k: "Revenue", v: "$300M" }, { k: "EBITDA", v: "$2M (nearly break-even)" }, { k: "Debt", v: "Crushing — near default" }, { k: "Seller", v: "Creditor committee" }],
      highlights: ["Iconic outdoor brand people still love", "Buy the debt/assets very cheaply", "Fixable: too many stores, too much old stock"],
      risks: ["Creditors, lawyers, and time pressure", "Piles of unsellable old inventory", "Could fail and liquidate entirely"],
      cta: "Close the report" },
    { kind: "decision", id: "nw-fit", phase: "Sourcing", situation: ["A near-bankrupt retailer - reckless or opportunity? Diane wants your read."],
      question: "What's the distressed thesis here?",
      choices: [
        { text: "A loved brand, bought cheap, freed of its crushing debt", points: 2, rel: 2, feedback: "Distressed investing: the business can be fine once the balance sheet is fixed. You buy the brand for pennies.", effect: { buildQuality: 4 } },
        { text: "It's dying - never touch a bankruptcy", points: 0, feedback: "Some of the best returns come from good brands with bad balance sheets. The debt is the problem, not the brand." },
        { text: "Only worth it to liquidate for parts", points: 1, feedback: "Liquidation kills a valuable brand. The bigger prize is reviving it - that's the real special-situations skill." },
      ] },
    { kind: "decision", id: "nw-structure", phase: "Negotiation", from: DIANE, subject: "Structure — debt is the enemy here",
      situation: ["This company is drowning in debt already. The whole point is to REDUCE leverage, not add it."],
      question: "How do you structure the buy?",
      choices: [
        { text: "Little new debt - the fix is a clean balance sheet", points: 2, feedback: "You're rescuing it FROM debt. Loading on more would repeat the mistake that broke it.", effect: { leverageMult: 1 } },
        { text: "Pile on new debt to minimize your check", points: 0, feedback: "Adding leverage to a company that just drowned in debt is how the rescue fails immediately.", effect: { leverageMult: 4 } },
        { text: "Moderate debt, business as usual", points: 1, feedback: "In a distressed deal, even 'moderate' new debt is risky. A near-cash balance sheet is the medicine.", effect: { leverageMult: 2.5 } },
      ] },
    { kind: "negotiation", id: "nw-loi", phase: "Negotiation",
      neg: { id: "nw-loi", title: "The deal — buy from the creditors", counterparty: "Howard Reyes", role: "Head of the creditor committee", youWant: "low", unit: "×", start: 4, floor: 2.5, resultVar: "entryMultiple",
        intro: ["The creditors are exhausted and want a clean, fast exit - but they'll fight a lowball.", "Howard: \"We've been through the wringer. We want out. But we're not giving it away. Your offer?\""],
        rounds: [
          { theirLine: "\"We're looking for about 4× on what little it earns.\"",
            choices: [
              { text: "Offer 2.8×, showing the old inventory and losing stores", reply: "\"...hard to argue with the dead inventory. There's room.\"", move: 0.7, rel: 5, points: 2, feedback: "In distress, the ugly facts are your leverage - a fact-based low bid they can accept." },
              { text: "Split at 3.6× to move fast", reply: "\"Close to our ask - we'll take it.\"", move: 0.15, rel: 2, points: 1, feedback: "On a distressed asset you have real leverage - anchoring high wastes it." },
              { text: "Offer 1× - they're desperate", reply: "\"We'll liquidate before we take that.\"", move: 0.1, rel: -7, points: 0, feedback: "Push a tired creditor too far and they'll just liquidate out of spite." },
            ] },
          { theirLine: "\"Get us to a clean, certain close.\"",
            choices: [
              { text: "Offer speed and certainty — no financing risk", reply: "\"A sure, fast close is worth a lot to us. Deal.\"", move: 0.6, rel: 5, points: 2, feedback: "Exhausted creditors value certainty over the last dollar. Certainty is your close." },
              { text: "Nudge your price up to seal it", reply: "\"Fine, we'll take a bit more.\"", move: 0.3, rel: 2, points: 1, feedback: "Paying up works but wastes distressed leverage." },
              { text: "Stall to grind them further", reply: "\"We're done waiting. Liquidation it is.\"", move: 0.05, rel: -6, points: 0, feedback: "Distressed sellers have a breaking point - stalling can blow up the deal." },
            ] },
        ] } },
    { kind: "decision", id: "nw-dd", phase: "Diligence", subject: "The inventory problem",
      situation: ["Diligence confirms it: $40M of old, unsellable inventory clogging warehouses and cash. It's a big part of why they nearly failed."],
      question: "What's your plan for it?",
      choices: [
        { text: "Clear it fast at a discount to free up cash and space", points: 2, feedback: "Dead inventory ties up cash you need to revive the brand. Clearing it quickly is painful but essential.", effect: { buildQuality: 5, score: 1 } },
        { text: "Hold it and hope it sells at full price", points: 0, feedback: "Old gear doesn't recover value - it ties up cash and shelf space while you starve for both.", effect: { buildQuality: -5 } },
        { text: "Ignore it and focus only on new stock", points: 1, feedback: "You can't ignore $40M of clogged cash. Deal with the mess before it sinks the rescue." },
      ] },
    { kind: "milestone", id: "nw-closed", phase: "Closing", variant: "closed", title: "Rescued from the brink — now revive it",
      body: ["You buy Northwind cheap and wipe out the crushing debt. The brand survives - barely. Now turn survival into a comeback."] },
    { kind: "decision", id: "nw-v1", phase: "Value Creation", situation: ["A clean balance sheet buys you room. Where do you focus first?"],
      question: "Your first revival move?",
      choices: [
        { text: "Close the 30 dead stores, invest in the strong ones and online", points: 2, feedback: "Cut what's bleeding, feed what works, and meet outdoor shoppers online. The core rescue playbook.", effect: { buildQuality: 8, score: 1 } },
        { text: "Keep all 80 stores open for pride", points: 0, feedback: "Loyalty to money-losing stores is what nearly killed it. You must cut to save it.", effect: { buildQuality: -6 } },
        { text: "Cut marketing to save every possible dollar", points: 1, feedback: "A loved brand needs to remind people it's back. Starving marketing stalls the comeback.", effect: { buildQuality: -1 } },
      ] },
    { kind: "decision", id: "nw-v2", phase: "Value Creation", subject: "The brand is breathing again",
      situation: ["Leaner and debt-free, Northwind is profitable and its fans are returning. You can push the recovery further."],
      question: "How do you build on it?",
      choices: [
        { text: "Lean into the brand's story and its best product lines", points: 2, feedback: "Doubling down on what made people love it turns a rescue into a real, growing business.", effect: { buildQuality: 7, score: 1 } },
        { text: "Chase random trendy categories far from your roots", points: 0, feedback: "Wandering from the beloved core confuses the fans you just won back.", effect: { buildQuality: -4 } },
        { text: "Sit still and just collect the profit", points: 1, feedback: "Coasting after a rescue leaves the best of the comeback unearned." },
      ] },
    { kind: "email", id: "nw-exit", phase: "Exit", from: { name: "Marcus Lin", role: "Harbor Point Advisors" }, subject: "From bankruptcy to a bidding war",
      body: ["Northwind is unrecognizable: debt-free, lean, profitable, and loved again. A retail group and a brand-holding company both want it.", "You brought it back from the dead - now let's get paid for the resurrection."], cta: "Run the exit" },
    { kind: "negotiation", id: "nw-exit-neg", phase: "Exit",
      neg: { id: "nw-exit", title: "The exit — sell the resurrection", counterparty: "Summit Brands Group", role: "Buyer's M&A head", youWant: "high", unit: "×", start: 5, floor: 8, resultVar: "exitMultiple",
        intro: ["A brand group wants your revived retailer.", "\"A remarkable comeback. We're thinking 5×,\" they open."],
        rounds: [
          { theirLine: "\"5× for a recovered retailer feels right.\"",
            choices: [
              { text: "Show the debt-free growth and the loyal fanbase", reply: "\"...clean balance sheet and loyal customers - worth more. Higher.\"", move: 1.5, rel: 5, points: 2, feedback: "A rescued brand with a clean balance sheet is worth a premium - sell the transformation." },
              { text: "Ask for a bit more, vaguely", reply: "\"Small nudge.\"", move: 0.5, rel: 2, points: 1, feedback: "Vague ask, small move." },
              { text: "Demand a wild number now", reply: "\"Not serious.\"", move: 0.1, rel: -7, points: 0, feedback: "No basis, they walk." },
            ] },
          { theirLine: "\"Justify our top price.\"",
            choices: [
              { text: "Note a rival brand-holder is also bidding", reply: "\"...we won't lose the brand. Top of range.\"", move: 1.3, rel: 4, points: 2, feedback: "A live rival lifts a comeback story to full value." },
              { text: "Take the number", reply: "\"Certainty, smart.\"", move: 0, rel: 3, points: 1, feedback: "Fine, but you had a push left." },
              { text: "Bluff a fake bid", reply: "\"We checked - false.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff kills your price." },
            ] },
        ] } },
    { kind: "milestone", id: "nw-exit-done", phase: "Exit", variant: "exit", title: "Exited — resurrection complete",
      body: ["The retailer that was days from liquidation sells as a healthy, loved brand at a big multiple. You saved a company and made a fortune doing it.", "Diane: \"Distressed is where nerve meets skill. You had both.\""] },
  ],
}

/* ═══════════════ 9 · HEALTHCARE BUILD — BrightSmile ═══════════════ */
const healthcare: Deal = {
  id: "brightsmile", company: "BrightSmile", strategy: "Buy-and-build (healthcare)", sector: "Dental clinics",
  tagline: "Roll up family dental practices into one modern group — keep the dentists happy.", difficulty: "Core", emoji: "🦷",
  initVars: { ebitda: 9, leverageMult: 4, holdYears: 5 },
  steps: [
    { kind: "email", id: "bs-intro", phase: "Onboarding", from: DIANE, subject: "A healthcare buy-and-build",
      body: ["Dental care is thousands of solo practices with no back-office scale - perfect roll-up territory. BrightSmile is a small group we'd use as the platform, then add clinics.",
        "The catch in healthcare: you're nothing without the dentists. Keep them happy and take the paperwork off their plate. It's a proven, real PE playbook. Interested?"],
      cta: "Study BrightSmile" },
    { kind: "document", id: "bs-cim", phase: "Sourcing", title: "BrightSmile — platform profile", subtitle: "Dental services organization (DSO) · buy-and-build",
      rows: [{ k: "Clinics", v: "12 dental practices" }, { k: "Revenue", v: "$75M" }, { k: "EBITDA", v: "$9M" }, { k: "Dentists", v: "40, mostly staying on" }, { k: "Market", v: "1000s of solo practices to add" }],
      highlights: ["Steady, recession-resistant demand for dental care", "Huge scope to add clinics and centralize admin", "Dentists want to treat patients, not do paperwork"],
      risks: ["Lose the key dentists and you lose the patients", "Healthcare rules and compliance are strict", "Roll-ups fail without real integration"],
      cta: "Close the profile" },
    { kind: "decision", id: "bs-fit", phase: "Sourcing", situation: ["Why does a dental roll-up work? Diane wants the thesis - and the catch."],
      question: "What makes this build valuable?",
      choices: [
        { text: "Centralize admin so dentists just treat patients — then scale", points: 2, rel: 2, feedback: "Take the billing, HR and buying off the dentists' plates; they stay happy and productive as you add clinics.", effect: { buildQuality: 4 } },
        { text: "Cut dentist pay to boost margins", points: 0, feedback: "The dentists ARE the business. Squeeze them and they leave, taking the patients with them." },
        { text: "Just buy clinics fast, sort it out later", points: 1, feedback: "Buying without integrating or retaining dentists is how healthcare roll-ups quietly implode." },
      ] },
    { kind: "decision", id: "bs-structure", phase: "Negotiation", from: DIANE, subject: "Structure for a build",
      situation: ["You'll buy many clinics over years. Keep firepower and a cushion for a regulated, people-heavy business."],
      question: "How do you structure the platform?",
      choices: [
        { text: "Sensible debt, cash reserved for clinic acquisitions", points: 2, feedback: "Buy-and-build needs dry powder and a cushion for a regulated business. Don't over-lever the platform.", effect: { leverageMult: 4 } },
        { text: "Max debt to shrink your check now", points: 1, feedback: "Tapped out, you can't fund the add-on clinics that make the strategy work.", effect: { leverageMult: 5.5 } },
        { text: "No debt at all", points: 1, feedback: "Very safe, but you give up the leverage that lifts these returns. A balance was better.", effect: { leverageMult: 1 } },
      ] },
    { kind: "negotiation", id: "bs-loi", phase: "Negotiation",
      neg: { id: "bs-loi", title: "The LOI — buy the platform", counterparty: "Dr. Nadia Farah", role: "Founder dentist, BrightSmile", youWant: "low", unit: "×", start: 9, floor: 7, resultVar: "entryMultiple",
        intro: ["Dr. Farah built BrightSmile and cares that her dentists and patients are looked after.", "\"I want a partner who respects the clinical side,\" she says. \"And a fair price. Where do we begin?\""],
        rounds: [
          { theirLine: "\"Dental platforms trade around 9× - that's my number.\"",
            choices: [
              { text: "Offer 7.3× on comps, and a real dentist-first plan", reply: "\"...the number's grounded and I love the clinical respect. Let's talk.\"", move: 1, rel: 5, points: 2, feedback: "Fair comps plus a credible plan to protect the dentists - exactly what a founder-doctor wants." },
              { text: "Meet near 8.5× to keep her onside", reply: "\"Generous - I'll take it.\"", move: 0.3, rel: 3, points: 1, feedback: "Overpaying dents the MOIC. Respect and fairness, not extra dollars, win her." },
              { text: "Lowball 5× - it's just some clinics", reply: "\"You clearly don't value the clinical work. No.\"", move: 0.1, rel: -8, points: 0, feedback: "Dismissing the clinical side loses a founder-doctor instantly." },
            ] },
          { theirLine: "\"Close the gap and reassure my dentists.\"",
            choices: [
              { text: "Offer the dentists equity and clinical autonomy", reply: "\"Equity and autonomy? My dentists will stay for that. Deal.\"", move: 1, rel: 6, points: 2, feedback: "Giving the dentists a stake aligns and retains them - the whole ballgame in a DSO." },
              { text: "Just raise your price", reply: "\"We'll take the higher number.\"", move: 0.5, rel: 2, points: 1, feedback: "Paying up closes it but wastes value - and doesn't solve retention." },
              { text: "Pressure her to sign this week", reply: "\"Healthcare deals aren't rushed. Slow down.\"", move: 0.1, rel: -5, points: 0, feedback: "Rushing a careful founder-doctor backfires." },
            ] },
        ] } },
    { kind: "decision", id: "bs-retention", phase: "Diligence", subject: "A key dentist is wavering",
      situation: ["A top dentist with a huge patient following hears about the sale and worries a 'corporate' owner will ruin the care. She's thinking of leaving."],
      question: "How do you keep her?",
      choices: [
        { text: "Give her equity, autonomy, and less admin - in writing", points: 2, feedback: "Retain star dentists with ownership and clinical freedom. Lose her and you lose her patients - the asset.", effect: { buildQuality: 6, score: 1 } },
        { text: "Let her walk - dentists are replaceable", points: 0, feedback: "In a clinic, the dentist IS the patient relationship. Shrugging off a star is a costly mistake.", effect: { buildQuality: -6 } },
        { text: "Force her to stay with a strict contract", points: 1, feedback: "You can't force goodwill - a resentful dentist gives poor care and leaves anyway. Win her, don't cage her." },
      ] },
    { kind: "milestone", id: "bs-closed", phase: "Closing", variant: "closed", title: "Platform acquired — now build the group",
      body: ["BrightSmile is yours, dentists onside. Time to centralize the back office and start adding clinics - carefully."] },
    { kind: "decision", id: "bs-v1", phase: "Value Creation", situation: ["The clinics each do their own billing, buying, and scheduling - a mess. Where's the first win?"],
      question: "Your first build move?",
      choices: [
        { text: "Centralize billing, buying and admin so dentists just treat", points: 2, feedback: "Shared back-office lifts margin AND frees the dentists to see more patients - the core of the model.", effect: { buildQuality: 8, score: 1 } },
        { text: "Add ten clinics immediately, integrate later", points: 0, feedback: "Buying fast without integrating first creates chaos across a regulated business. Build the machine first.", effect: { buildQuality: -5 } },
        { text: "Cut clinical staff to save money", points: 1, feedback: "Cutting the people who deliver the care undermines the patient experience you're buying.", effect: { buildQuality: -2 } },
      ] },
    { kind: "decision", id: "bs-v2", phase: "Value Creation", subject: "The platform hums — time to add clinics",
      situation: ["With the back office humming, you can start acquiring solo practices to bolt on."],
      question: "How do you add clinics?",
      choices: [
        { text: "Buy good practices and keep their dentists with equity", points: 2, feedback: "Add clinics AND retain their dentists with ownership - patients and profit both come along.", effect: { buildQuality: 7, score: 1 } },
        { text: "Buy any clinic, cheap, and swap in new dentists", points: 0, feedback: "New faces send loyal patients elsewhere. You'd buy buildings and lose the practices.", effect: { buildQuality: -4 } },
        { text: "Stop at the platform - don't bother expanding", points: 1, feedback: "The scale from adding clinics is the whole point of a buy-and-build. Standing still wastes it." },
      ] },
    { kind: "email", id: "bs-exit", phase: "Exit", from: { name: "Marcus Lin", role: "Harbor Point Advisors" }, subject: "The group is ready to sell",
      body: ["BrightSmile is now a modern group - 30 clinics, one clean back office, happy dentists, steady growth. Bigger DSOs and a large PE fund are very interested.", "Scaled healthcare platforms command rich multiples. Let's sell."], cta: "Run the exit" },
    { kind: "negotiation", id: "bs-exit-neg", phase: "Exit",
      neg: { id: "bs-exit", title: "The exit — sell the scaled group", counterparty: "National Dental Partners", role: "Buyer's M&A head", youWant: "high", unit: "×", start: 9, floor: 12, resultVar: "exitMultiple",
        intro: ["A national DSO wants your scaled, well-run group.", "\"Impressive platform. We're at 9×,\" their head of M&A opens."],
        rounds: [
          { theirLine: "\"9× is strong for dental.\"",
            choices: [
              { text: "Show the scale, clean systems, and dentist retention", reply: "\"...a platform this clean with dentists locked in is rare. Higher.\"", move: 1.5, rel: 5, points: 2, feedback: "Scale plus retained dentists is exactly what a big DSO pays up for. Sell the build." },
              { text: "Ask for more, vaguely", reply: "\"Small nudge.\"", move: 0.5, rel: 2, points: 1, feedback: "Vague ask, small move." },
              { text: "Demand a wild jump now", reply: "\"Not serious.\"", move: 0.1, rel: -7, points: 0, feedback: "No basis, they walk." },
            ] },
          { theirLine: "\"Justify our top multiple.\"",
            choices: [
              { text: "Note a big PE fund is also bidding", reply: "\"...we won't lose it to a fund. Top of range.\"", move: 1.3, rel: 4, points: 2, feedback: "Competition lifts a scaled platform to full value." },
              { text: "Take the number", reply: "\"Certainty, smart.\"", move: 0, rel: 3, points: 1, feedback: "Fine, but you had a push left." },
              { text: "Bluff a fake bid", reply: "\"We checked - false.\"", move: -0.3, rel: -9, points: 0, feedback: "A checkable bluff kills your price." },
            ] },
        ] } },
    { kind: "milestone", id: "bs-exit-done", phase: "Exit", variant: "exit", title: "Exited — the build pays off",
      body: ["Twelve clinics became thirty, all on one modern platform with dentists who chose to stay. It sells to a national group at a premium.", "Diane: \"You scaled healthcare without losing the humans who deliver it. That's the whole trick.\""] },
  ],
}

export const PE_DEALS: Deal[] = [turnaround, rollup, carveout, takePrivate, growth, family, distressed, healthcare]
