// ════════════════════════════════════════════════════════════════════
// AP MICROECONOMICS — elective course track (additive; not state-required)
// Based on the College Board AP Microeconomics framework. Lesson prose is
// auto-generated by the shared content engine; the 3-question quizzes here are
// hand-authored. Units/lessons are track-tagged "ap-micro" and filtered out of
// the Florida track everywhere.
// ════════════════════════════════════════════════════════════════════

import { Lesson, UnitInfo, QuizQuestion, LessonCategory } from "@/types"

interface ApLessonSpec {
  num: string
  title: string
  description: string
  quiz: [QuizQuestion, QuizQuestion, QuizQuestion]
}

interface ApUnitSpec {
  unitNumber: number
  id: string
  title: string
  examWeight: string
  category: LessonCategory
  challenge?: string // stock-simulator / lab / business-mode tie-in
  lessons: ApLessonSpec[]
}

// Helper to keep quiz authoring compact.
const q = (id: string, question: string, options: string[], correctAnswer: number, explanation: string): QuizQuestion =>
  ({ id, question, options, correctAnswer, explanation })

const AP_MICRO_SPEC: ApUnitSpec[] = [
  // ─── UNIT 1 ────────────────────────────────────────────────────────
  {
    unitNumber: 1, id: "apm-1", title: "Basic Economic Concepts", examWeight: "12–15%",
    category: "micro-basics",
    challenge: "Open Micro-Business mode and list the trade-offs and opportunity cost of your next budget decision.",
    lessons: [
      {
        num: "1.1", title: "Scarcity and Economic Thinking",
        description: "Limited resources vs. unlimited wants, the three economic questions, factors of production, and opportunity cost.",
        quiz: [
          q("apm-1-1-q1", "What is the fundamental economic problem that forces every society to make choices?", ["Inflation", "Scarcity", "Unemployment", "Taxation"], 1, "Scarcity — unlimited wants but limited resources — is why choices and trade-offs exist."),
          q("apm-1-1-q2", "Which of the following is a factor of production?", ["Money", "Stocks", "Labor", "Profit"], 2, "The four factors of production are land, labor, capital, and entrepreneurship. Money is not a factor — it buys them."),
          q("apm-1-1-q3", "You spend Saturday working a $60 shift instead of going to a free concert you'd value at $40. What is the opportunity cost of working?", ["$60", "$40 (the concert you gave up)", "$100", "$20"], 1, "Opportunity cost is the value of the next-best alternative given up — the concert worth $40."),
        ],
      },
      {
        num: "1.2", title: "Resource Allocation and Economic Systems",
        description: "Market, command, and mixed economies, how each answers the three questions, and the role of prices.",
        quiz: [
          q("apm-1-2-q1", "In a market economy, what mainly decides what gets produced?", ["Government planners", "Prices and the profit motive", "Random chance", "International law"], 1, "Markets use prices and profit signals to allocate resources, not central planners."),
          q("apm-1-2-q2", "A command economy is best described as one where…", ["consumers vote with their dollars", "the government owns resources and plans production", "there is no government at all", "prices are set by supply and demand"], 1, "In a command economy the government owns resources and centrally plans the answers to the three economic questions."),
          q("apm-1-2-q3", "Prices in a market act primarily as…", ["a tax on consumers", "signals that allocate resources", "a government tool only", "a barrier to trade"], 1, "Prices signal scarcity and value, guiding resources toward their most-valued uses."),
        ],
      },
      {
        num: "1.3", title: "The Production Possibilities Curve (PPC)",
        description: "Trade-offs between two goods, efficiency, points on/inside/outside the curve, growth, and increasing opportunity cost.",
        quiz: [
          q("apm-1-3-q1", "A point INSIDE the production possibilities curve represents…", ["efficient production", "unattainable production", "inefficient or underused resources", "economic growth"], 2, "Points inside the PPC mean resources are idle or used inefficiently."),
          q("apm-1-3-q2", "What does a point OUTSIDE the current PPC represent?", ["A recession", "Currently unattainable production", "Productive efficiency", "Zero opportunity cost"], 1, "Points beyond the curve are unattainable with current resources/technology — until the curve shifts out."),
          q("apm-1-3-q3", "A PPC that bows outward (concave) reflects…", ["constant opportunity cost", "increasing opportunity cost", "decreasing opportunity cost", "zero scarcity"], 1, "A concave PPC shows increasing opportunity cost because resources aren't equally suited to both goods."),
        ],
      },
      {
        num: "1.4", title: "Comparative Advantage and Gains from Trade",
        description: "Absolute vs. comparative advantage, opportunity cost per unit, specialization, and the terms of trade.",
        quiz: [
          q("apm-1-4-q1", "A country should specialize in the good for which it has…", ["the absolute advantage", "the lower opportunity cost (comparative advantage)", "the highest price", "the most workers"], 1, "Specialization follows comparative advantage — the lower opportunity cost — not absolute advantage."),
          q("apm-1-4-q2", "Ana makes 10 bracelets OR 5 necklaces per hour. Her opportunity cost of 1 necklace is…", ["2 bracelets", "5 bracelets", "0.5 bracelets", "10 bracelets"], 0, "Giving up 5 necklaces frees 10 bracelets, so 1 necklace costs 10/5 = 2 bracelets."),
          q("apm-1-4-q3", "Mutually beneficial trade occurs when the terms of trade are…", ["always equal to one", "between the two parties' opportunity costs", "set by the government", "higher than both costs"], 1, "Both parties gain when the trading ratio falls between their individual opportunity costs."),
        ],
      },
      {
        num: "1.5", title: "Cost-Benefit Analysis",
        description: "Explicit vs. implicit costs, economic vs. accounting profit, and why sunk costs shouldn't affect decisions.",
        quiz: [
          q("apm-1-5-q1", "Economic profit differs from accounting profit because it also subtracts…", ["explicit costs", "implicit (opportunity) costs", "taxes", "fixed costs"], 1, "Economic profit subtracts BOTH explicit and implicit costs; accounting profit subtracts only explicit costs."),
          q("apm-1-5-q2", "A sunk cost is one that…", ["can be recovered later", "has already been incurred and cannot be recovered", "only appears in the long run", "equals marginal cost"], 1, "Sunk costs are already spent and unrecoverable, so they should not influence current decisions."),
          q("apm-1-5-q3", "You already bought a $15 movie ticket (non-refundable) but now feel sick. The $15 should…", ["force you to attend anyway", "be ignored — it's a sunk cost", "be doubled in your decision", "be added to your benefit"], 1, "The $15 is sunk; the rational choice depends only on remaining costs and benefits."),
        ],
      },
      {
        num: "1.6", title: "Marginal Analysis and Consumer Choice",
        description: "Marginal benefit vs. marginal cost, the MB ≥ MC decision rule, and diminishing marginal utility.",
        quiz: [
          q("apm-1-6-q1", "A rational decision-maker keeps doing an activity as long as…", ["marginal benefit ≥ marginal cost", "total benefit is positive", "marginal cost is zero", "average cost falls"], 0, "Act while MB ≥ MC; stop where MB = MC to maximize net benefit."),
          q("apm-1-6-q2", "Diminishing marginal utility means that each additional unit consumed…", ["adds more satisfaction than the last", "adds less additional satisfaction than the last", "has zero cost", "raises the price"], 1, "Marginal utility falls as you consume more of the same good."),
          q("apm-1-6-q3", "The optimal quantity to consume or produce is where…", ["MB = MC", "total cost = 0", "MB is highest", "price = 0"], 0, "Net benefit is maximized at the quantity where marginal benefit equals marginal cost."),
        ],
      },
    ],
  },

  // ─── UNIT 2 ────────────────────────────────────────────────────────
  {
    unitNumber: 2, id: "apm-2", title: "Supply and Demand", examWeight: "20–25%",
    category: "micro-supply-demand",
    challenge: "In the Stock simulator, watch how a news headline moves a stock's price — a real-time demand shift in action.",
    lessons: [
      {
        num: "2.1", title: "Demand",
        description: "The law of demand, demand shifters, normal vs. inferior goods, substitutes/complements, and shifts vs. movements.",
        quiz: [
          q("apm-2-1-q1", "The law of demand states that, all else equal, when price rises, quantity demanded…", ["rises", "falls", "stays the same", "becomes zero"], 1, "Price and quantity demanded move in opposite directions — the demand curve slopes down."),
          q("apm-2-1-q2", "A fall in the price of a good causes…", ["a shift of the demand curve", "a movement along the demand curve", "demand to disappear", "supply to shift"], 1, "A change in the good's own price is a movement ALONG the curve, not a shift."),
          q("apm-2-1-q3", "Coffee and tea are substitutes. If the price of coffee rises, the demand for tea will…", ["decrease", "increase", "not change", "become inelastic"], 1, "Higher coffee prices push buyers toward tea, increasing tea demand (a rightward shift)."),
        ],
      },
      {
        num: "2.2", title: "Supply",
        description: "The law of supply, supply shifters (input costs, technology, taxes/subsidies), and shifts vs. movements.",
        quiz: [
          q("apm-2-2-q1", "The law of supply says price and quantity supplied are…", ["inversely related", "directly (positively) related", "unrelated", "always equal"], 1, "Higher prices make production more profitable, so quantity supplied rises — an upward-sloping curve."),
          q("apm-2-2-q2", "Which of these shifts the supply curve to the right?", ["A new tax on producers", "A rise in input costs", "An improvement in technology", "A fall in the number of sellers"], 2, "Better technology lowers production costs, increasing supply (rightward shift)."),
          q("apm-2-2-q3", "A government subsidy to producers will…", ["shift supply left", "shift supply right", "move along the supply curve", "shift demand right"], 1, "A subsidy lowers per-unit cost, increasing supply (rightward shift)."),
        ],
      },
      {
        num: "2.3", title: "Elasticity",
        description: "Price elasticity of demand and supply, elastic/inelastic/unit elastic, determinants, and the total-revenue test.",
        quiz: [
          q("apm-2-3-q1", "Demand is described as INELASTIC when…", ["%ΔQ > %ΔP (elasticity > 1)", "%ΔQ < %ΔP (elasticity < 1)", "elasticity is infinite", "price never changes"], 1, "Inelastic demand means quantity responds little to price (|elasticity| < 1) — e.g., necessities."),
          q("apm-2-3-q2", "Which good is likely to have the MOST elastic demand?", ["Insulin", "Salt", "A specific brand of soda with many substitutes", "Gasoline in the short run"], 2, "Many close substitutes make demand more elastic; necessities with few substitutes are inelastic."),
          q("apm-2-3-q3", "If demand is elastic and a firm raises its price, total revenue will…", ["increase", "decrease", "stay the same", "become zero"], 1, "When demand is elastic, a price increase reduces quantity enough that total revenue falls."),
        ],
      },
      {
        num: "2.4", title: "Market Equilibrium, Disequilibrium, and Changes",
        description: "Equilibrium price/quantity, surpluses and shortages, and predicting changes from supply/demand shifts.",
        quiz: [
          q("apm-2-4-q1", "A shortage occurs when the price is…", ["above equilibrium", "below equilibrium", "exactly at equilibrium", "irrelevant to quantity"], 1, "Below equilibrium, quantity demanded exceeds quantity supplied — a shortage that pushes price up."),
          q("apm-2-4-q2", "If demand increases while supply is unchanged, the equilibrium price and quantity will…", ["both fall", "both rise", "price rises, quantity falls", "price falls, quantity rises"], 1, "A rightward demand shift raises both equilibrium price and quantity."),
          q("apm-2-4-q3", "When BOTH demand and supply increase, the change in equilibrium quantity is ___ and price is ___.", ["certain to rise; indeterminate", "indeterminate; certain to rise", "certain to fall; certain to rise", "indeterminate; indeterminate"], 0, "Both shifts raise quantity (certain up), but the price change depends on the relative sizes (indeterminate)."),
        ],
      },
      {
        num: "2.5", title: "Government Intervention in Markets",
        description: "Price ceilings and floors, excise taxes and incidence, subsidies, and deadweight loss.",
        quiz: [
          q("apm-2-5-q1", "An effective (binding) price ceiling is set…", ["above equilibrium and creates a surplus", "below equilibrium and creates a shortage", "at equilibrium", "below equilibrium and creates a surplus"], 1, "A binding ceiling (e.g., rent control) sits below equilibrium, causing a persistent shortage."),
          q("apm-2-5-q2", "A minimum wage is an example of a binding price floor that can cause…", ["a labor shortage", "a labor surplus (unemployment)", "lower prices", "no effect ever"], 1, "A binding floor above equilibrium creates a surplus — in labor markets, that's unemployment."),
          q("apm-2-5-q3", "An excise tax on a good generally creates…", ["a surplus for consumers", "deadweight loss", "more total surplus", "lower prices for buyers"], 1, "Taxes drive a wedge between buyers and sellers, reducing quantity and creating deadweight loss."),
        ],
      },
      {
        num: "2.6", title: "International Trade and Public Policy",
        description: "Comparative advantage as the basis for trade, tariffs and quotas, and effects on consumer/producer/total surplus.",
        quiz: [
          q("apm-2-6-q1", "A tariff is…", ["a tax on imported goods", "a limit on import quantity", "a subsidy to foreigners", "a ban on exports"], 0, "A tariff is a tax on imports; a quota is a quantity limit."),
          q("apm-2-6-q2", "When a country opens to trade and becomes an importer, who clearly gains?", ["Domestic producers", "Domestic consumers", "No one", "Only the government"], 1, "Importing lowers the domestic price, so consumers gain (and gain more than producers lose — net welfare rises)."),
          q("apm-2-6-q3", "Tariffs and quotas generally…", ["increase total surplus", "create deadweight loss", "help consumers", "eliminate scarcity"], 1, "Trade barriers raise prices and reduce quantity traded, creating deadweight loss."),
        ],
      },
    ],
  },

  // ─── UNIT 3 ────────────────────────────────────────────────────────
  {
    unitNumber: 3, id: "apm-3", title: "Production, Cost, and Perfect Competition", examWeight: "22–25%",
    category: "micro-production",
    challenge: "Pick a company in the Stock simulator and analyze its profit margin — is price above or below average total cost?",
    lessons: [
      {
        num: "3.1", title: "The Production Function",
        description: "Inputs/outputs, total/marginal/average product, diminishing marginal returns, and short vs. long run.",
        quiz: [
          q("apm-3-1-q1", "The law of diminishing marginal returns says that adding more of a variable input (with fixed inputs) eventually causes…", ["marginal product to rise forever", "marginal product to fall", "total product to fall immediately", "fixed costs to rise"], 1, "Beyond a point, each extra worker adds less additional output — marginal product declines."),
          q("apm-3-1-q2", "The short run is defined as a period in which…", ["all inputs are variable", "at least one input is fixed", "no production occurs", "costs are zero"], 1, "In the short run at least one input (often capital) is fixed; in the long run all inputs vary."),
          q("apm-3-1-q3", "Marginal product is…", ["total output divided by workers", "the extra output from one more unit of input", "always equal to average product", "the price of output"], 1, "Marginal product is the additional output produced by one more unit of the variable input."),
        ],
      },
      {
        num: "3.2", title: "Short-Run Production Costs",
        description: "Fixed/variable/total costs, AFC/AVC/ATC, marginal cost, and the U-shaped ATC curve.",
        quiz: [
          q("apm-3-2-q1", "Which cost does NOT change with the quantity produced in the short run?", ["Variable cost", "Marginal cost", "Fixed cost", "Total cost"], 2, "Fixed costs (e.g., rent) stay the same regardless of output in the short run."),
          q("apm-3-2-q2", "The marginal cost curve intersects the ATC curve at…", ["ATC's maximum", "ATC's minimum", "the origin", "the fixed cost line"], 1, "MC crosses ATC (and AVC) at their minimum points."),
          q("apm-3-2-q3", "Average total cost equals…", ["AFC + AVC", "AFC − AVC", "MC × Q", "TC × Q"], 0, "ATC = AFC + AVC = total cost divided by quantity."),
        ],
      },
      {
        num: "3.3", title: "Long-Run Production Costs",
        description: "All costs variable in the long run, the LRATC curve, economies/diseconomies of scale, and minimum efficient scale.",
        quiz: [
          q("apm-3-3-q1", "Economies of scale occur when, as output rises, long-run average total cost…", ["rises", "falls", "stays constant", "becomes negative"], 1, "Economies of scale mean LRATC falls as the firm grows (spreading costs, specialization)."),
          q("apm-3-3-q2", "In the long run…", ["all inputs are variable", "fixed costs dominate", "no firm can enter", "output is fixed"], 0, "By definition, all inputs (and thus all costs) are variable in the long run."),
          q("apm-3-3-q3", "Diseconomies of scale typically arise from…", ["greater specialization", "bulk discounts", "coordination and management problems as the firm grows too large", "lower input prices"], 2, "When firms get too big, management and coordination problems raise LRATC."),
        ],
      },
      {
        num: "3.4", title: "Types of Profit",
        description: "Accounting vs. economic profit, normal profit (zero economic profit), and implicit costs.",
        quiz: [
          q("apm-3-4-q1", "Normal profit corresponds to…", ["positive economic profit", "zero economic profit", "negative accounting profit", "maximum revenue"], 1, "Normal profit means economic profit is zero — the firm covers all explicit AND implicit costs."),
          q("apm-3-4-q2", "A firm earning zero economic profit is…", ["going out of business", "covering all opportunity costs and staying in", "earning zero accounting profit", "a monopoly"], 1, "Zero economic profit still covers implicit costs, so the owner is doing as well as their next-best option."),
          q("apm-3-4-q3", "Implicit costs are…", ["out-of-pocket payments", "the opportunity cost of owner-supplied resources", "always zero", "the same as fixed costs"], 1, "Implicit costs are the value of resources the owner could have used elsewhere (e.g., their own time)."),
        ],
      },
      {
        num: "3.5", title: "Profit Maximization",
        description: "The MR = MC rule, finding the profit-maximizing quantity, and calculating profit as (P − ATC) × Q.",
        quiz: [
          q("apm-3-5-q1", "A firm maximizes profit by producing where…", ["MR = MC", "ATC is lowest", "TR is highest", "price = 0"], 0, "Profit is maximized at the quantity where marginal revenue equals marginal cost."),
          q("apm-3-5-q2", "Profit can be calculated as…", ["(P − ATC) × Q", "P × Q only", "ATC × Q", "MC − MR"], 0, "Per-unit profit (P − ATC) times quantity gives total profit; equivalently TR − TC."),
          q("apm-3-5-q3", "At the profit-maximizing quantity, if price is below ATC, the firm is…", ["earning a profit", "earning a loss", "breaking even", "shutting down for sure"], 1, "If P < ATC at the best quantity, the firm is making a loss (though it may still operate if P ≥ AVC)."),
        ],
      },
      {
        num: "3.6", title: "Perfect Competition",
        description: "Price takers, the horizontal firm demand curve, short-run outcomes, the shutdown rule (P < AVC), and long-run zero profit.",
        quiz: [
          q("apm-3-6-q1", "A perfectly competitive firm is a 'price taker,' so its demand curve is…", ["downward sloping", "horizontal at the market price", "vertical", "upward sloping"], 1, "Each firm is tiny relative to the market, so it faces a horizontal demand curve at the market price (P = MR)."),
          q("apm-3-6-q2", "A competitive firm should shut down in the short run if price falls below…", ["average total cost", "average variable cost", "marginal cost", "fixed cost"], 1, "Shut down if P < AVC — otherwise operating at least covers some variable costs."),
          q("apm-3-6-q3", "In long-run equilibrium, perfectly competitive firms earn…", ["positive economic profit", "zero economic profit", "negative accounting profit", "maximum profit"], 1, "Free entry and exit drive economic profit to zero in the long run."),
        ],
      },
    ],
  },

  // ─── UNIT 4 ────────────────────────────────────────────────────────
  {
    unitNumber: 4, id: "apm-4", title: "Imperfect Competition", examWeight: "15–22%",
    category: "micro-imperfect",
    challenge: "In the Stock simulator, hunt for a monopoly or an oligopoly among real companies and note its source of market power.",
    lessons: [
      {
        num: "4.1", title: "Monopoly",
        description: "Sources of monopoly power, MR < P, profit maximization, deadweight loss, and natural monopoly.",
        quiz: [
          q("apm-4-1-q1", "For a monopoly, marginal revenue is…", ["equal to price", "greater than price", "less than price", "always zero"], 2, "Because a monopolist must lower price to sell more, MR < P (the MR curve lies below demand)."),
          q("apm-4-1-q2", "Compared with perfect competition, a monopoly produces…", ["more output at a lower price", "less output at a higher price", "the same output", "output at zero price"], 1, "Monopolies restrict output and charge a higher price, creating deadweight loss."),
          q("apm-4-1-q3", "A natural monopoly arises when…", ["the government bans competitors", "one firm can supply the whole market at lower cost due to economies of scale", "there are many small firms", "products are identical"], 1, "Natural monopolies have such large economies of scale that one firm serves the market most cheaply."),
        ],
      },
      {
        num: "4.2", title: "Price Discrimination",
        description: "First/second/third degree price discrimination, required conditions, and effects on surplus.",
        quiz: [
          q("apm-4-2-q1", "Price discrimination requires that the firm…", ["be a price taker", "have market power and prevent resale", "sell identical prices to all", "face perfect competition"], 1, "A firm needs market power, the ability to segment buyers, and to stop resale (arbitrage)."),
          q("apm-4-2-q2", "Student and senior discounts at a movie theater are examples of…", ["first-degree price discrimination", "third-degree price discrimination", "a price ceiling", "perfect competition"], 1, "Charging different groups different prices based on their elasticity is third-degree price discrimination."),
          q("apm-4-2-q3", "Perfect (first-degree) price discrimination converts consumer surplus into…", ["deadweight loss", "producer surplus", "government revenue", "nothing"], 1, "Charging each buyer their maximum willingness to pay transfers consumer surplus to the producer."),
        ],
      },
      {
        num: "4.3", title: "Monopolistic Competition",
        description: "Many sellers with differentiated products, short-run profit/loss, long-run zero profit, and excess capacity.",
        quiz: [
          q("apm-4-3-q1", "A key feature of monopolistic competition is…", ["identical products", "differentiated products and many sellers", "a single seller", "no entry or exit"], 1, "Many firms sell similar-but-differentiated products with easy entry and exit."),
          q("apm-4-3-q2", "In the long run, monopolistically competitive firms earn…", ["large profits", "zero economic profit", "guaranteed losses", "the same as a monopoly"], 1, "Easy entry competes away profit, so long-run economic profit is zero (like perfect competition)."),
          q("apm-4-3-q3", "Monopolistic competition is productively inefficient because firms have…", ["zero costs", "excess capacity (don't produce at minimum ATC)", "perfect information", "no advertising"], 1, "These firms produce below the minimum-ATC output, leaving excess capacity."),
        ],
      },
      {
        num: "4.4", title: "Oligopoly and Game Theory",
        description: "Interdependence, collusion and cartels, the Prisoner's Dilemma, Nash equilibrium, and dominant strategies.",
        quiz: [
          q("apm-4-4-q1", "Oligopoly is characterized by…", ["a single seller", "many tiny sellers", "a few large interdependent sellers", "identical products only"], 2, "A few large firms whose decisions depend on each other define oligopoly."),
          q("apm-4-4-q2", "In a Nash equilibrium…", ["firms always cooperate", "no player can improve by changing strategy alone", "the government sets prices", "there is always a price war"], 1, "At a Nash equilibrium, each player's choice is best given the others' choices — no one benefits from a unilateral change."),
          q("apm-4-4-q3", "Cartels (like OPEC) tend to be unstable because…", ["demand is always elastic", "each member has an incentive to cheat by overproducing", "governments subsidize them", "there are too many buyers"], 1, "Each member can gain by secretly producing more than its quota, which breaks down the cartel."),
        ],
      },
    ],
  },

  // ─── UNIT 5 ────────────────────────────────────────────────────────
  {
    unitNumber: 5, id: "apm-5", title: "Factor Markets", examWeight: "10–13%",
    category: "micro-factor-markets",
    challenge: "In Micro-Business mode, decide how many 'workers' (tasks) to take on — you're hiring up to where extra value ≥ extra cost.",
    lessons: [
      {
        num: "5.1", title: "Introduction to Factor Markets",
        description: "Labor/capital/land markets, derived demand, and marginal revenue product (MRP = MR × MP).",
        quiz: [
          q("apm-5-1-q1", "Demand for labor is called a 'derived demand' because it comes from…", ["the wage rate", "the demand for the output workers produce", "government policy", "the supply of labor"], 1, "Firms hire workers because of the value of what those workers produce — demand derives from the product market."),
          q("apm-5-1-q2", "Marginal revenue product (MRP) of labor equals…", ["wage × hours", "marginal product × marginal revenue", "total revenue ÷ workers", "price ÷ quantity"], 1, "MRP = marginal product of labor × marginal revenue (or price in competition)."),
          q("apm-5-1-q3", "MRP measures…", ["the cost of one more worker", "the extra revenue from hiring one more worker", "total output", "the wage floor"], 1, "MRP is the additional revenue a firm earns by employing one more unit of the factor."),
        ],
      },
      {
        num: "5.2", title: "Changes in Factor Demand and Supply",
        description: "What shifts labor demand and supply, and wage determination in a competitive labor market.",
        quiz: [
          q("apm-5-2-q1", "An increase in worker productivity will…", ["shift labor demand left", "shift labor demand right (raising wages)", "shift labor supply right", "lower the output price"], 1, "More productive workers have higher MRP, increasing labor demand and the equilibrium wage."),
          q("apm-5-2-q2", "Which shifts the labor SUPPLY curve?", ["A change in the output price", "A change in worker productivity", "A change in the number of available workers", "A change in the firm's technology"], 2, "Labor supply shifts with the number of workers, preferences, and wages in other jobs."),
          q("apm-5-2-q3", "In a competitive labor market, the wage is set by…", ["the single largest employer", "the intersection of labor supply and demand", "the government only", "the firm's fixed costs"], 1, "Competitive wages are determined where market labor supply meets market labor demand."),
        ],
      },
      {
        num: "5.3", title: "Profit Maximizing in Competitive Factor Markets",
        description: "Hiring where MRP = MRC, the MRP curve as labor demand, and the least-cost input rule.",
        quiz: [
          q("apm-5-3-q1", "A firm in a competitive labor market hires workers up to the point where…", ["MRP = wage (MRC)", "MRP = 0", "wage = 0", "MP is highest"], 0, "Hire until the marginal revenue product equals the marginal resource cost (the wage)."),
          q("apm-5-3-q2", "For a competitive employer, the labor demand curve is the…", ["supply curve", "MRP curve", "ATC curve", "total revenue curve"], 1, "A firm's labor demand is its downward-sloping MRP curve."),
          q("apm-5-3-q3", "The least-cost rule for combining inputs is satisfied when…", ["MP per dollar is equal across all inputs", "all inputs cost the same", "only labor is used", "MRP = 0 for capital"], 0, "Cost is minimized when the marginal product per dollar spent is equal for every input."),
        ],
      },
      {
        num: "5.4", title: "Monopsonistic Markets",
        description: "Single buyer of labor, monopsony vs. competition, and effects on wages, employment, and efficiency.",
        quiz: [
          q("apm-5-4-q1", "A monopsony is a market with…", ["a single seller", "a single buyer (e.g., of labor)", "many buyers and sellers", "no government"], 1, "A monopsony has one dominant buyer — for example, the only major employer in a town."),
          q("apm-5-4-q2", "Compared to a competitive labor market, a monopsony pays a wage that is…", ["higher and hires more", "lower and hires fewer workers", "the same", "zero"], 1, "A monopsonist restricts hiring and pays below the competitive wage."),
          q("apm-5-4-q3", "A 'company town' where one firm employs nearly everyone is a real-world example of…", ["perfect competition", "monopsony", "a price ceiling", "a cartel"], 1, "When one firm is essentially the only buyer of local labor, it has monopsony power."),
        ],
      },
    ],
  },

  // ─── UNIT 6 ────────────────────────────────────────────────────────
  {
    unitNumber: 6, id: "apm-6", title: "Market Failure and the Role of Government", examWeight: "8–13%",
    category: "micro-market-failure",
    challenge: "In the Stock simulator, find a company facing regulatory or ESG risk — that's a negative externality the market is pricing in.",
    lessons: [
      {
        num: "6.1", title: "Socially Efficient and Inefficient Outcomes",
        description: "Allocative efficiency (P = MC), productive efficiency, consumer/producer surplus, and deadweight loss.",
        quiz: [
          q("apm-6-1-q1", "Allocative efficiency is achieved when…", ["price = marginal cost", "ATC is at its minimum", "profit is maximized", "supply = 0"], 0, "Allocative efficiency means the last unit's price equals its marginal cost (P = MC)."),
          q("apm-6-1-q2", "Total surplus is the sum of…", ["taxes and subsidies", "consumer surplus and producer surplus", "fixed and variable costs", "revenue and profit"], 1, "Total welfare = consumer surplus + producer surplus; it's maximized at the efficient quantity."),
          q("apm-6-1-q3", "Deadweight loss represents…", ["extra profit", "lost total surplus from producing the wrong quantity", "government revenue", "consumer savings"], 1, "Deadweight loss is the welfare lost when output is above or below the efficient level."),
        ],
      },
      {
        num: "6.2", title: "Externalities",
        description: "Negative and positive externalities, over/under-production, and Pigouvian taxes, subsidies, and the Coase theorem.",
        quiz: [
          q("apm-6-2-q1", "A factory polluting a river is an example of a…", ["positive externality", "negative externality", "public good", "price floor"], 1, "Pollution imposes costs on third parties — a negative externality."),
          q("apm-6-2-q2", "Markets tend to ___ goods with positive externalities (like vaccination).", ["overproduce", "underproduce", "perfectly produce", "ban"], 1, "Because buyers ignore the external benefits, the market underproduces goods with positive externalities."),
          q("apm-6-2-q3", "A Pigouvian tax is used to correct a…", ["positive externality", "negative externality", "shortage", "price ceiling"], 1, "A per-unit tax equal to the external cost makes producers internalize a negative externality."),
        ],
      },
      {
        num: "6.3", title: "Public and Private Goods",
        description: "Excludable/rival classifications, the free-rider problem, and the tragedy of the commons.",
        quiz: [
          q("apm-6-3-q1", "A public good is…", ["rival and excludable", "non-rival and non-excludable", "always provided by firms", "the same as a club good"], 1, "Public goods (e.g., national defense) are non-rival and non-excludable."),
          q("apm-6-3-q2", "The free-rider problem explains why markets underprovide…", ["private goods", "public goods", "luxury goods", "inferior goods"], 1, "People can enjoy a non-excludable good without paying, so firms underprovide it — government often steps in."),
          q("apm-6-3-q3", "The 'tragedy of the commons' applies to…", ["excludable private goods", "common resources that are rival but non-excludable", "public goods only", "monopoly pricing"], 1, "Shared, non-excludable but rival resources (like fisheries) get overused and depleted."),
        ],
      },
      {
        num: "6.4", title: "Government Intervention in Market Structures",
        description: "Antitrust laws, regulating natural monopolies, rent-seeking, and government failure.",
        quiz: [
          q("apm-6-4-q1", "Antitrust laws are designed to…", ["create monopolies", "promote competition and limit monopoly power", "set all prices", "ban trade"], 1, "Antitrust policy prevents and breaks up anti-competitive behavior and monopolies."),
          q("apm-6-4-q2", "Regulators often make a natural monopoly price at average total cost in order to…", ["maximize the monopoly's profit", "let it break even while lowering price/raising output", "create deadweight loss", "ban the firm"], 1, "Average-cost pricing gives the firm a fair (normal) return while improving the outcome for consumers."),
          q("apm-6-4-q3", "'Rent-seeking' refers to…", ["paying rent on an apartment", "using resources to gain special privileges rather than create value", "a price ceiling on housing", "earning normal profit"], 1, "Rent-seeking spends resources to capture favors (e.g., lobbying) instead of producing value — it can cause government failure."),
        ],
      },
      {
        num: "6.5", title: "Income and Wealth Inequality",
        description: "Lorenz curve and Gini coefficient, sources of inequality, redistribution, and the equity-efficiency trade-off.",
        quiz: [
          q("apm-6-5-q1", "The Gini coefficient measures…", ["inflation", "income/wealth inequality", "unemployment", "GDP growth"], 1, "The Gini coefficient (0 = perfect equality, 1 = perfect inequality) summarizes income distribution."),
          q("apm-6-5-q2", "A Lorenz curve that bows farther from the line of equality indicates…", ["less inequality", "more inequality", "zero poverty", "higher efficiency"], 1, "The farther the Lorenz curve is from the 45° line, the greater the inequality."),
          q("apm-6-5-q3", "Redistributive programs often involve a trade-off between…", ["equity and efficiency", "supply and demand", "price and quantity", "imports and exports"], 0, "Taxes and transfers can reduce inequality (equity) but may dull incentives (efficiency)."),
        ],
      },
    ],
  },
]

// ─── Build exported arrays/maps from the spec ───────────────────────────

export const AP_MICRO_UNITS: UnitInfo[] = AP_MICRO_SPEC.map((u) => ({
  id: u.id,
  unitNumber: u.unitNumber,
  title: u.title,
  level: u.unitNumber,
  levelTitle: `AP Micro · ${u.examWeight}`,
  categories: [u.category],
  orderIndex: 100 + u.unitNumber, // distinct from Florida orderIndex
  track: "ap-micro",
}))

export const AP_MICRO_LESSONS: Lesson[] = AP_MICRO_SPEC.flatMap((u) =>
  u.lessons.map((l, i) => ({
    id: `${u.id}-${i + 1}`,
    title: l.title,
    description: l.description,
    category: u.category,
    level: "explorer",
    unitId: u.id,
    lessonNumber: l.num,
    reward: 100,
    content: "",
    duration: 3,
    completed: false,
    track: "ap-micro" as const,
  }))
)

// lessonId -> authored 3-question quiz, overlaid onto auto-generated content.
export const AP_MICRO_QUIZZES: Record<string, QuizQuestion[]> = Object.fromEntries(
  AP_MICRO_SPEC.flatMap((u) =>
    u.lessons.map((l, i) => [`${u.id}-${i + 1}`, l.quiz] as const)
  )
)

// unitId -> simulator / lab / business-mode challenge tie-in.
export const AP_UNIT_CHALLENGES: Record<string, string> = Object.fromEntries(
  AP_MICRO_SPEC.filter((u) => u.challenge).map((u) => [u.id, u.challenge as string])
)

export const AP_MICRO_UNIT_IDS = new Set(AP_MICRO_UNITS.map((u) => u.id))
